---
title: "Bring diversity data together & modify files"
output: github_document
editor_options: 
  chunk_output_type: console
---
### Load packages
```{r, Bringing everything together load modifying files packages}
library(dplyr)
library(parallel)
library(stringr)
library(reshape2)
library(phytools)
library(tidyr)
```

### Load in files
```{r, Bringing everything together load in modifying files}
env_by_lake <- read.csv("/Users/bailey/Documents/research/Fish_Biodiversity/data/collection/environment/env_by_lake.csv")

# Fish present in the marine lakes and reference pool by lake code. fish_matched and fish_matched2
pres_abs_by_lake <- read.csv("/Users/bailey/Documents/research/Fish_Biodiversity/data/collection/fish/pres_abs/fish_presence_matrix_by_lake.csv")

# Fish present in the marine lakes and reference pool by species. fish_matched and fish_matched2
pres_abs_by_species <- read.csv("/Users/bailey/Documents/research/Fish_Biodiversity/data/collection/fish/pres_abs/fish_presence_matrix_by_species.csv")

# Fish present in marine lakes only
surveyed_sites_fish <- read.csv("/Users/bailey/Documents/research/Fish_Biodiversity/data/collection/fish/pres_abs/surveyed_site_presence_by_species.csv")

# Ocean site fish presence by species 
ocean_fish <- read.csv("/Users/bailey/Documents/research/Fish_Biodiversity/data/collection/fish/pres_abs/ocean_site_presence_by_species.csv")

# Holomictic fish presence by species 
holomictic_fish <- read.csv("/Users/bailey/Documents/research/Fish_Biodiversity/data/collection/fish/pres_abs/holomictic_presence_by_species.csv")

# Meromictic fish presence by species 
meromictic_fish <- read.csv("/Users/bailey/Documents/research/Fish_Biodiversity/data/collection/fish/pres_abs/meromictic_presence_by_species.csv")

# Mixed fish presence by species 
mixed_fish <- read.csv("/Users/bailey/Documents/research/Fish_Biodiversity/data/collection/fish/pres_abs/mixed_presence_by_species.csv")

# Stratified fish presence by species 
stratified_fish <- read.csv("/Users/bailey/Documents/research/Fish_Biodiversity/data/collection/fish/pres_abs/stratified_presence_by_species.csv")

# Surveyed sites fish presence by species each in separate files
BCM_fish <- read.csv("/Users/bailey/Documents/research/Fish_Biodiversity/data/collection/fish/pres_abs/BCM_fish.csv")
CLM_fish <- read.csv("/Users/bailey/Documents/research/Fish_Biodiversity/data/collection/fish/pres_abs/CLM_fish.csv")
FLK_fish <- read.csv("/Users/bailey/Documents/research/Fish_Biodiversity/data/collection/fish/pres_abs/FLK_fish.csv")
GLK_fish <- read.csv("/Users/bailey/Documents/research/Fish_Biodiversity/data/collection/fish/pres_abs/GLK_fish.csv")
HLM_fish <- read.csv("/Users/bailey/Documents/research/Fish_Biodiversity/data/collection/fish/pres_abs/HLM_fish.csv")
HLO_fish <- read.csv("/Users/bailey/Documents/research/Fish_Biodiversity/data/collection/fish/pres_abs/HLO_fish.csv")
IBK_fish <- read.csv("/Users/bailey/Documents/research/Fish_Biodiversity/data/collection/fish/pres_abs/IBK_fish.csv")
LLN_fish <- read.csv("/Users/bailey/Documents/research/Fish_Biodiversity/data/collection/fish/pres_abs/LLN_fish.csv")
LCN_fish <- read.csv("/Users/bailey/Documents/research/Fish_Biodiversity/data/collection/fish/pres_abs/LCN_fish.csv")
MLN_fish <- read.csv("/Users/bailey/Documents/research/Fish_Biodiversity/data/collection/fish/pres_abs/MLN_fish.csv")
NCN_fish <- read.csv("/Users/bailey/Documents/research/Fish_Biodiversity/data/collection/fish/pres_abs/NCN_fish.csv")
NLK_fish <- read.csv("/Users/bailey/Documents/research/Fish_Biodiversity/data/collection/fish/pres_abs/NLK_fish.csv")
NLN_fish <- read.csv("/Users/bailey/Documents/research/Fish_Biodiversity/data/collection/fish/pres_abs/NLN_fish.csv")
NLU_fish <- read.csv("/Users/bailey/Documents/research/Fish_Biodiversity/data/collection/fish/pres_abs/NLU_fish.csv")
OLO_fish <- read.csv("/Users/bailey/Documents/research/Fish_Biodiversity/data/collection/fish/pres_abs/OLO_fish.csv")
OCO_fish <- read.csv("/Users/bailey/Documents/research/Fish_Biodiversity/data/collection/fish/pres_abs/OCO_fish.csv")
OTM_fish <- read.csv("/Users/bailey/Documents/research/Fish_Biodiversity/data/collection/fish/pres_abs/OTM_fish.csv")
OCM_fish <- read.csv("/Users/bailey/Documents/research/Fish_Biodiversity/data/collection/fish/pres_abs/OCM_fish.csv")
RCA_fish <- read.csv("/Users/bailey/Documents/research/Fish_Biodiversity/data/collection/fish/pres_abs/RCA_fish.csv")
SLN_fish <- read.csv("/Users/bailey/Documents/research/Fish_Biodiversity/data/collection/fish/pres_abs/SLN_fish.csv")
TLN_fish <- read.csv("/Users/bailey/Documents/research/Fish_Biodiversity/data/collection/fish/pres_abs/TLN_fish.csv")
ULN_fish <- read.csv("/Users/bailey/Documents/research/Fish_Biodiversity/data/collection/fish/pres_abs/ULN_fish.csv")

# Phylogenetic tree of species present in marine lakes, tree
tree <- read.tree("/Users/bailey/Documents/research/Fish_Biodiversity/data/collection/fish/phylo/palau_fish_tree.tre")

# Traits for fish present in the marine lakes and reference pool, fish_traits_complete_matched and fish_traits_complete_matched2
species_functional_traits <- read.csv("/Users/bailey/Documents/research/Fish_Biodiversity/data/collection/fish/traits/final_traits_gnathostomata.csv")
```

## Check species names
- Check that names are consistent across files. 
```{r, Check species names across files}
## Check species names in incidence matrix, trait matrix, and phylogenetic tree
# Check trait data with occurrence data
# If differences are found then check meromictic, holomictic, and ocean site dataframes too
not_present_trait <- setdiff(species_functional_traits$Species, pres_abs_by_species$X)
not_present_trait

# Check tree data with occurrence data
# If differences are found then check meromictic, holomictic, and ocean site dataframes too
not_present_tree <- setdiff(tree$tip.label, pres_abs_by_species$X)
not_present_tree

# Check tree data with trait data
not_present <- setdiff(tree$tip.label, species_functional_traits$Species)
not_present

# Find what lakes pres/abs and env data
site_env_only <- setdiff(env_by_lake$X, pres_abs_by_lake$X)
site_env_only

# Delete lakes from above with no pres/abs data, LCM, LSM, SLM, ULU
# env_by_lake <- env_by_lake[-c(8, 11, 23, 27),]
```

## Modify environmental data
```{r, Modify environment data}
# Contains environmental data for lakes sampled from
env_by_lake$Location_type <- factor(env_by_lake$Location_type, levels = c("Reference", "Ocean", "Mixed", "Stratified"))

env_by_lake$logArea <- log(env_by_lake$surface_area_m2)

row.names(env_by_lake) <- env_by_lake$X
env <- env_by_lake
env$C <- env$temperature_median
env$S <- env$salinity_median
env$O <- env$oxygen_median
env$minD <- env$distance_to_ocean_min_m
env$M <- env$max_depth
env$LA <- env$logArea

scaled_env <- as.data.frame(scale(env[,c(2,6,8,10,22:32)]))

# Create a formula for aggregation
formula <- as.formula(paste(". ~ Location_type"))

# Use the aggregate function to calculate the mean for each variable by Location_type
Location_type_env <- aggregate(formula, data = env[, c(2,4,6,8,10,19,22:32)], FUN = mean)
```

## Modify incidence matrices
```{r, Modify incidence matrices}
# Presence/absence by lake
row.names(pres_abs_by_lake) <- pres_abs_by_lake$X
pres_abs_by_lake[,c(2:1725)] <- sapply(pres_abs_by_lake[,c(2:1725)], as.numeric)
presabs_lake <- pres_abs_by_lake[,-1]

# Kept this here because HLM is holomictic but is mixed, so it differs between datasets #
com_presabs_lake <- presabs_lake
com_presabs_lake[24,] <- colSums(com_presabs_lake[c(7,9,11,16,18:19),])
rownames(com_presabs_lake)[rownames(com_presabs_lake) == "24"] <- "Ocean sites"
com_presabs_lake[25,] <- colSums(com_presabs_lake[c(3,5:6,8,10,13:15,23),])
rownames(com_presabs_lake)[rownames(com_presabs_lake) == "25"] <- "Holomictic lakes"
com_presabs_lake[26,] <- colSums(com_presabs_lake[c(1:2,4,12,17,21,22),])
rownames(com_presabs_lake)[rownames(com_presabs_lake) == "26"] <- "Meromictic lakes"

strat_presabs_lake <- presabs_lake
strat_presabs_lake[24,] <- colSums(strat_presabs_lake[c(7,9,11,16,18:19),])
rownames(strat_presabs_lake)[rownames(strat_presabs_lake) == "24"] <- "Ocean sites"
strat_presabs_lake[25,] <- colSums(strat_presabs_lake[c(3,6,8,10,13:15,23),])
rownames(strat_presabs_lake)[rownames(strat_presabs_lake) == "25"] <- "Mixed lakes"
strat_presabs_lake[26,] <- colSums(strat_presabs_lake[c(1:2,4,5,12,17,21,22),])
rownames(strat_presabs_lake)[rownames(strat_presabs_lake) == "26"] <- "Stratified lakes"

# Add total number of fish per site and how many environments each species is present in
pres_abs_lake_sums <- pres_abs_by_lake
pres_abs_lake_sums$row_sum <- rowSums(pres_abs_lake_sums[,-1])
pres_abs_lake_sums[24,-1] <- colSums(pres_abs_lake_sums[,-1])
site_sums <- pres_abs_lake_sums[, c(1,1726)]
species_sums <- pres_abs_lake_sums[c(24),-1]
rownames(species_sums)[rownames(species_sums) == "24"] <- "col_sum"
pres_abs_lake_sums <- pres_abs_lake_sums[,-1]

#Merge the species richness with env data
SR_env <- merge(site_sums, env, by = 'X', sort = F)
row.names(SR_env) <- SR_env$X
# data <- SR_env[,c(1:2,25)]
# row.names(data) <- data$X
# data <- data[,-1]
# colnames(data)[1] <- 's'
# colnames(data)[2] <- 'a'
# name <- "Palau fish data"
# SAR <- list(name, data)
# data(power);data(expo);data(negexpo);data(monod);data(ratio);data(logist);data(lomolino);data(weibull)
# mods <- c("power","expo","negexpo","monod","logist","ratio","lomolino","weibull")
# resAverage <- multiSAR(modelList = mods, SAR)


# Presence/absence by species
row.names(pres_abs_by_species) <- pres_abs_by_species$X
pres_abs_by_species[,c(2:24)] <- sapply(pres_abs_by_species[,c(2:24)], as.numeric)
presabs_species <- pres_abs_by_species[,-c(1)]

pres_abs_species_sums <- pres_abs_by_species
pres_abs_species_sums$row_sum <- rowSums(pres_abs_species_sums[,-1])
pres_abs_species_sums <- pres_abs_species_sums[,-1]


# Surveyed Locations
surveyed_sites_fish[,c(2:23)] <- sapply(surveyed_sites_fish[,c(2:23)], as.numeric)
row.names(surveyed_sites_fish) <- surveyed_sites_fish$X
surveyed_sites_species <- surveyed_sites_fish[,-1]
# Create dataframe with lakes as rows
surveyed_sites_lake <- as.data.frame(t(surveyed_sites_species))
# Reorder lake names alphabetically
surveyed_sites_lake <- surveyed_sites_lake[order(row.names(surveyed_sites_lake)),]

# Kept this here because HLM is holomictic but is mixed, so it differs between datasets #
surveyed_sites_com_abund <- surveyed_sites_lake
surveyed_sites_com_abund[25,] <- colSums(surveyed_sites_com_abund[c(7,9,11,16,18:19),])
rownames(surveyed_sites_com_abund)[rownames(surveyed_sites_com_abund) == "23"] <- "Ocean sites"
surveyed_sites_com_abund[24,] <- colSums(surveyed_sites_com_abund[c(3,5:6,8,10,13:15,22),])
rownames(surveyed_sites_com_abund)[rownames(surveyed_sites_com_abund) == "24"] <- "Holomictic lakes"
surveyed_sites_com_abund[23,] <- colSums(surveyed_sites_com_abund[c(1:2,4,12,17,20,21),])
rownames(surveyed_sites_com_abund)[rownames(surveyed_sites_com_abund) == "25"] <- "Meromictic lakes"
surveyed_sites_com <- surveyed_sites_com_abund
surveyed_sites_com[surveyed_sites_com > "1"] <- 1

surveyed_sites_strat_abund <- surveyed_sites_lake
surveyed_sites_strat_abund[25,] <- colSums(surveyed_sites_strat_abund[c(7,9,11,16,18:19),])
rownames(surveyed_sites_strat_abund)[rownames(surveyed_sites_strat_abund) == "23"] <- "Ocean sites"
surveyed_sites_strat_abund[24,] <- colSums(surveyed_sites_strat_abund[c(3,6,8,10,13:15,22),])
rownames(surveyed_sites_strat_abund)[rownames(surveyed_sites_strat_abund) == "24"] <- "Mixed lakes"
surveyed_sites_strat_abund[23,] <- colSums(surveyed_sites_strat_abund[c(1:2,4,5,12,17,20,21),])
rownames(surveyed_sites_strat_abund)[rownames(surveyed_sites_strat_abund) == "25"] <- "Stratified lakes"
surveyed_sites_strat <- surveyed_sites_strat_abund
surveyed_sites_strat[surveyed_sites_strat > "1"] <- 1

surveyed_fish <- surveyed_sites_fish[,1]
surveyed_fishe <- surveyed_sites_fish[,-c(8,9,15)]
surveyed_fishe <- surveyed_fishe[which(rowSums(surveyed_fishe[, -1]) > 0),]
surveyed_fishe <- surveyed_fishe[,1]
surveyed_fishb <- surveyed_sites_fish[,-c(10)]
surveyed_fishb <- surveyed_fishb[which(rowSums(surveyed_fishb[, -1]) > 0),]
surveyed_fishb <- surveyed_fishb[,1]


# Ocean sites surveyed
ocean_fish[,c(2:7)] <- sapply(ocean_fish[,c(2:7)], as.numeric)
row.names(ocean_fish) <- ocean_fish$X
ocean_species <- ocean_fish[,-1]
ocean_species <- ocean_species[order(row.names(ocean_species)),]
# Create dataframe with lakes as rows
ocean_site <- as.data.frame(t(ocean_species))
# Reorder lake names alphabetically
ocean_site <- ocean_site[order(row.names(ocean_site)),]


# Holomictic lake surveyed sites
holomictic_fish[,c(2:10)] <- sapply(holomictic_fish[,c(2:10)], as.numeric)
row.names(holomictic_fish) <- holomictic_fish$X
holomictic_species <- holomictic_fish[,-1]
holomictic_species <- holomictic_species[order(row.names(holomictic_species)),]
# Create dataframe with lakes as rows
holomictic_lake <- as.data.frame(t(holomictic_species))
# Reorder lake names alphabetically
holomictic_lake <- holomictic_lake[order(row.names(holomictic_lake)),]


# Meromictic lake surveyed sites
meromictic_fish[,c(2:7)] <- sapply(meromictic_fish[,c(2:7)], as.numeric)
row.names(meromictic_fish) <- meromictic_fish$X
meromictic_species <- meromictic_fish[,-1]
meromictic_species <- meromictic_species[order(row.names(meromictic_species)),]
# Create dataframe with lakes as rows
meromictic_lake <- as.data.frame(t(meromictic_species))
# Reorder lake names alphabetically
meromictic_lake <- meromictic_lake[order(row.names(meromictic_lake)),]


# Mixed lake surveyed sites
mixed_fish[,c(2:9)] <- sapply(mixed_fish[,c(2:9)], as.numeric)
row.names(mixed_fish) <- mixed_fish$X
mixed_species <- mixed_fish[,-1]
mixed_species <- mixed_species[order(row.names(mixed_species)),]
# Create dataframe with lakes as rows
mixed_lake <- as.data.frame(t(mixed_species))
# Reorder lake names alphabetically
mixed_lake <- mixed_lake[order(row.names(mixed_lake)),]


# Stratified lake surveyed sites
stratified_fish[,c(2:9)] <- sapply(stratified_fish[,c(2:9)], as.numeric)
row.names(stratified_fish) <- stratified_fish$X
stratified_species <- stratified_fish[,-1]
stratified_species <- stratified_species[order(row.names(stratified_species)),]
# Create dataframe with lakes as rows
stratified_lake <- as.data.frame(t(stratified_species))
# Reorder lake names alphabetically
stratified_lake <- stratified_lake[order(row.names(stratified_lake)),]


# Give sites pres abs matrices row names and make files with only species presence
row.names(BCM_fish) <- BCM_fish$X
BCM_species <- BCM_fish["BCM"]
row.names(CLM_fish) <- CLM_fish$X
CLM_species <- CLM_fish["CLM"]
row.names(FLK_fish) <- FLK_fish$X
FLK_species <- FLK_fish["FLK"]
row.names(GLK_fish) <- GLK_fish$X
GLK_species <- GLK_fish["GLK"]
row.names(HLM_fish) <- HLM_fish$X
HLM_species <- HLM_fish["HLM"]
row.names(HLO_fish) <- HLO_fish$X
HLO_species <- HLO_fish["HLO"]
row.names(IBK_fish) <- IBK_fish$X
IBK_species <- IBK_fish["IBK"]
row.names(LLN_fish) <- LLN_fish$X
LLN_species <- LLN_fish["LLN"]
row.names(LCN_fish) <- LCN_fish$X
LCN_species <- LCN_fish["LCN"]
row.names(MLN_fish) <- MLN_fish$X
MLN_species <- MLN_fish["MLN"]
row.names(NCN_fish) <- NCN_fish$X
NCN_species <- NCN_fish["NCN"]
row.names(NLK_fish) <- NLK_fish$X
NLK_species <- NLK_fish["NLK"]
row.names(NLN_fish) <- NLN_fish$X
NLN_species <- NLN_fish["NLN"]
row.names(NLU_fish) <- NLU_fish$X
NLU_species <- NLU_fish["NLU"]
row.names(OLO_fish) <- OLO_fish$X
OLO_species <- OLO_fish["OLO"]
row.names(OCO_fish) <- OCO_fish$X
OCO_species <- OCO_fish["OCO"]
row.names(OTM_fish) <- OTM_fish$X
OTM_species <- OTM_fish["OTM"]
row.names(OCM_fish) <- OCM_fish$X
OCM_species <- OCM_fish["OCM"]
row.names(RCA_fish) <- RCA_fish$X
RCA_species <- RCA_fish["RCA"]
row.names(SLN_fish) <- SLN_fish$X
SLN_species <- SLN_fish["SLN"]
row.names(TLN_fish) <- TLN_fish$X
TLN_species <- TLN_fish["TLN"]
row.names(ULN_fish) <- ULN_fish$X
ULN_species <- ULN_fish["ULN"]
```

## Modify phylogeny
```{r, Modify phylogeny}
# Make a tree of only surveyed site species and trees that include only sites with environmental or biogeographic data
stree <- drop.tip(tree, setdiff(tree$tip.label, surveyed_fish), trim.internal = TRUE, rooted = is.rooted(tree))

# Env tree
etree <- drop.tip(tree, setdiff(tree$tip.label, surveyed_fishe), trim.internal = TRUE, rooted = is.rooted(tree))

# Biogeo tree
btree <- drop.tip(tree, setdiff(tree$tip.label, surveyed_fishb), trim.internal = TRUE, rooted = is.rooted(tree))
```

## Modify trait data frames
```{r, Modify trait data}
# Salt, brack, fresh amalgamation
# Edit column trait information to simplify for analyses
species_functional_traits$WaterPref <- "all"
species_functional_traits$WaterPref[species_functional_traits$Fresh > 0 & species_functional_traits$Brack < 1 & species_functional_traits$Saltwater < 1] <- "fresh"
species_functional_traits$WaterPref[species_functional_traits$Fresh > 0 & species_functional_traits$Brack > 0 & species_functional_traits$Saltwater < 1] <- "fresh-brack"
species_functional_traits$WaterPref[species_functional_traits$Fresh < 1 & species_functional_traits$Brack > 0 & species_functional_traits$Saltwater < 1] <- "brack"
species_functional_traits$WaterPref[species_functional_traits$Fresh < 1 & species_functional_traits$Brack > 0 & species_functional_traits$Saltwater > 0] <- "brack-salt"
species_functional_traits$WaterPref[species_functional_traits$Fresh < 1 & species_functional_traits$Brack < 1 & species_functional_traits$Saltwater > 0] <- "salt"
species_functional_traits$WaterPref[species_functional_traits$Fresh > 0 & species_functional_traits$Brack < 1 & species_functional_traits$Saltwater > 0] <- "fresh-salt"

# Categorical variables
species_functional_traits <- species_functional_traits %>%
    mutate(BodyShapeI = dplyr::recode(BodyShapeI, 'elongated' = '4e', "short and / or deep" = "2s", 'fusiform / normal' =  '3f', 'eel-like' = '5l', 'other' = '1o'))
species_functional_traits <- species_functional_traits %>%
    mutate(DemersPelag = dplyr::recode(DemersPelag, 'bathydemersal' = '7bd', 'benthopelagic' = '6bp', 'demersal' = '5d', 'pelagic' =  '3p', 'pelagic-neritic' = '2pn', 'pelagic-oceanic' = '4po', 'reef-associated' = '1r'))
species_functional_traits <- species_functional_traits %>%
    mutate(FeedingPath = dplyr::recode(FeedingPath, 'benthic' = 'b', 'pelagic' = 'p'))
species_functional_traits <- species_functional_traits %>%
    mutate(RepGuild1 = dplyr::recode(RepGuild1, 'guarders' = '2g', 'bearers' = '1b', 'nonguarders' =  '3n'))
species_functional_traits <- species_functional_traits %>%
    mutate(RepGuild2 = dplyr::recode(RepGuild2, 'internal live bearers' = '1ib', 'Internal live bearers' = '1ib', 'open water/substratum egg scatterers' = '6s', 'nesters' =  '3n', 'Nesters' =  '3n', 'brood hiders' = '5h', 'clutch tenders' = '4t', 'external brooders' = '2eb'))
species_functional_traits <- species_functional_traits %>%
    mutate(ParentalCare = dplyr::recode(ParentalCare, 'none' = '4n', 'paternal' = '3p', 'maternal' = '2m', 'biparental' = '1b'))
species_functional_traits <- species_functional_traits %>%
    mutate(WaterPref = dplyr::recode(WaterPref, 'all' = '3a', 'salt' = '1s', 'brack-salt' = '2bs', 'brack' = '4b', 'fresh-brack' = '5fb', 'fresh' = '6f'))

# Operculum 
species_functional_traits$OperculumPresent[species_functional_traits$OperculumPresent > 0] <- "yes"
species_functional_traits$OperculumPresent[species_functional_traits$OperculumPresent < 1] <- "no"

# DorsalSpinesMean
species_functional_traits$DorsalSpinesMean <- rowMeans(species_functional_traits[c("DorsalSpinesMax", "DorsalSpinesMin")])

# Get rid of Salt, brack, fresh column and Dorsal Spines columns
drop <- c("Saltwater", "Brack", "Fresh", "DorsalSpinesMax", "DorsalSpinesMin")
species_functional_traits <- species_functional_traits[, -which(names(species_functional_traits) %in% drop)]

# Edit fields
factor <- c("BodyShapeI", "DemersPelag", "OperculumPresent", "FeedingPath", "RepGuild1", "RepGuild2", "ParentalCare", "WaterPref")
species_functional_traits[,factor] <- lapply(species_functional_traits[,factor], function(x) as.factor(tolower(trimws(x))))
# species_functional_traits$BodyShapeI <- as.factor(species_functional_traits$BodyShapeI)
# species_functional_traits$DemersPelag <- as.factor(species_functional_traits$DemersPelag)
# species_functional_traits$OperculumPresent <- as.factor(species_functional_traits$OperculumPresent)
# species_functional_traits$FeedingPath <- as.factor(species_functional_traits$FeedingPath)
# species_functional_traits$RepGuild1 <- as.factor(species_functional_traits$RepGuild1)
# species_functional_traits$RepGuild2 <- as.factor(species_functional_traits$RepGuild2)
# species_functional_traits$ParentalCare <- as.factor(species_functional_traits$ParentalCare)
# species_functional_traits$WaterPref <- as.factor(species_functional_traits$WaterPref)

str(species_functional_traits)

# Make Species column the row names and get rid of columns that are not traits
row.names(species_functional_traits) <- species_functional_traits$X
# Reorder species names alphabetically
species_functional_traits <- species_functional_traits[order(row.names(species_functional_traits)),]
# Trim off other taxonomic levels other than species name
traits <- species_functional_traits[,-c(2:6)]
rs <- pres_abs_by_species[,c(1,21)]
rt <- full_join(traits, rs, by = "X")
rt$LocationSums <- rt$REF
rt <- rt[,-17]
rt$Strat <- "R"
rt <- cbind(rt, env[20, c(2,4,6,8,10,19,22:32)])
# Warning message:
# In data.frame(..., check.names = FALSE) :
#   row names were found from a short variable and have been discarded
rt <- rt %>% relocate(Location_type, .before = temperature_median)
traits <- traits[,-1]

# Surveyed
surveyed_sites_traits <- species_functional_traits[species_functional_traits$X %in% surveyed_sites_fish$X,]
str(surveyed_sites_traits)
# Make Species column the row names and get rid of columns that are not traits
row.names(surveyed_sites_traits) <- surveyed_sites_traits$X
# Reorder species names alphabetically
surveyed_sites_traits <- surveyed_sites_traits[order(row.names(surveyed_sites_traits)),]
# Trim off other taxonomic levels other than species name
straits <- surveyed_sites_traits[,-c(2:6)]
surveyed_sites_fish$LocationSums <- rowSums(surveyed_sites_fish[,-1])
# # ss <- surveyed_sites_fish[,c(1,24)]
# # st <- full_join(straits, ss, by = "X")
# # st$Strat <- "S"
straits <- straits[,-1]
```

## Modify Location_type trait data frames
```{r, Modify Location_type data frames}
# Ocean
ocean_traits <- species_functional_traits[species_functional_traits$X %in% ocean_fish$X,]
str(ocean_traits)
# Make Species column the row names and get rid of columns that are not traits
row.names(ocean_traits) <- ocean_traits$X
# Reorder species names alphabetically
ocean_traits <- ocean_traits[order(row.names(ocean_traits)),]
# Trim off other taxonomic levels other than species name
otraits <- ocean_traits[,-c(2:6)]
ocean_fish$LocationSums <- rowSums(ocean_fish[,-1])
os <- ocean_fish[,c(1,8)]
ot <- full_join(otraits, os, by = "X")
ot$Strat <- "O"
ot <- cbind(ot, Location_type_env[1,])
# Warning message:
# In data.frame(..., check.names = FALSE) :
#   row names were found from a short variable and have been discarded
otraits <- otraits[,-1]

# Mixed
mixed_traits <- species_functional_traits[species_functional_traits$X %in% mixed_fish$X,]
str(mixed_traits)
# Make Species column the row names and get rid of columns that are not traits
row.names(mixed_traits) <- mixed_traits$X
# Reorder species names alphabetically
mixed_traits <- mixed_traits[order(row.names(mixed_traits)),]
# Trim off other taxonomic levels other than species name
mxtraits <- mixed_traits[,-c(2:6)]
mixed_fish$LocationSums <- rowSums(mixed_fish[,-1])
mxs <- mixed_fish[,c(1,10)]
mxt <- full_join(mxtraits, mxs, by = "X")
mxt$Strat <- "M"
mxt <- cbind(mxt, Location_type_env[2,])
# Warning message:
# In data.frame(..., check.names = FALSE) :
#   row names were found from a short variable and have been discarded
mxtraits <- mxtraits[,-1]


# Stratified
stratified_traits <- species_functional_traits[species_functional_traits$X %in% stratified_fish$X,]
str(stratified_traits)
# Make Species column the row names and get rid of columns that are not traits
row.names(stratified_traits) <- stratified_traits$X
# Reorder species names alphabetically
stratified_traits <- stratified_traits[order(row.names(stratified_traits)),]
# Trim off other taxonomic levels other than species name
sttraits <- stratified_traits[,-c(2:6)]
stratified_fish$LocationSums <- rowSums(stratified_fish[,-1])
sts <- stratified_fish[,c(1,10)]
stt <- full_join(sttraits, sts, by = "X")
stt$Strat <- "S"
stt <- cbind(stt, Location_type_env[3,])
# Warning message:
# In data.frame(..., check.names = FALSE) :
#   row names were found from a short variable and have been discarded
sttraits <- sttraits[,-1]
```

### Modify Location_type trait data
```{r, Modify Location_type trait data}
# All
Location_type_at <- rbind(rt, ot, mxt, stt)

Location_type_at$Strat <- factor(Location_type_at$Strat, levels = c("R", "O", "M", "S"))

Location_type_at_weighted <- Location_type_at %>%
  group_by(Location_type) %>%
  uncount(weights = LocationSums)

Location_type_st <- rbind(ot, mxt, stt)

Location_type_st$Strat <- factor(Location_type_st$Strat, levels = c("O", "M", "S"))

Location_type_st_weighted <- Location_type_st %>%
  group_by(Location_type) %>%
  uncount(weights = LocationSums)
```

### Location_type trait data tests
```{r, Location_type trait data tests}
# # Apply the normality test function to each column in your dataframe
# shapiro_results <- lapply(Location_type_at[,c(2:17)], test_normality)
# 
# ## For numerical traits
# # Create an empty vector to store numerical trait p-values
# Location_type_at_nt_p_values <- c()
# 
# # Loop through each trait (numerical variable)
# for (trait in colnames(Location_type_at[,c(4:10,12:13)])) {
#   # Use the Kruskal-Wallis test
#   kruskal_result <- kruskal.test(Location_type_at[[trait]] ~ Location_type, data = Location_type_at)
#   # Extract and store the p-value
#   Location_type_at_nt_p_values <- c(Location_type_at_nt_p_values, kruskal_result$p.value)
# }
# 
# # Display the p-values for each trait
# Location_type_at_nt_p_values
# 
# ## For categorical traits
# # Create an empty vector to store Location_type_ategorical trait p-values
# Location_type_at_ct_p_values <- numeric()
# 
# # Loop through each categorical variable (trait) in your data
# for (trait in colnames(Location_type_at[,c(2:3,11,14:17)])) {
#   # Create a contingency table for the current trait and Location_type
#   contingency_table <- table(Location_type_at$Location_type, Location_type_at[[trait]])
#   # Perform Fisher's Exact Test
#   fisher_test_result <- fisher.test(contingency_table, simulate.p.value = T)
#   # Extract and store the p-value
#   p_value <- fisher_test_result$p.value
#   Location_type_at_ct_p_values <- c(Location_type_at_ct_p_values, p_value)
# }
# 
# # Display the p-values for each trait
# Location_type_at_ct_p_values
# 
# # Example usage
# Location_type_at_traits <- colnames(st[,c(2:17)])
# Location_type_at_env_vars <- colnames(st[,c(20:36)])
# Location_type_at_test_results <- perform_tests(Location_type_at, Location_type_at_traits, Location_type_at_env_vars)
# 
# # Usage example
# Location_type_at_p_values <- extract_p_values(Location_type_at_test_results)
```

## Modify site trait data frames
```{r, Modify site trait data frames}
# BCM
BCM_traits <- species_functional_traits[species_functional_traits$X %in% BCM_fish$X,]
str(BCM_traits)
# Reorder species alphabetically
BCM_traits <- BCM_traits[order(row.names(BCM_traits)),]
# Trim off other taxonomic levels other than species name
BCMt <- BCM_traits[,-c(1:6)]
# BCMt$Location <- "BCM"
BCMt <- cbind(BCMt, env[1,])

# CLM
CLM_traits <- species_functional_traits[species_functional_traits$X %in% CLM_fish$X,]
str(CLM_traits)
# Reorder species alphabetically
CLM_traits <- CLM_traits[order(row.names(CLM_traits)),]
# Trim off other taxonomic levels other than species name
CLMt <- CLM_traits[,-c(1:6)]
# CLMt$Location <- "CLM"
CLMt <- cbind(CLMt, env[2,])

# FLK
FLK_traits <- species_functional_traits[species_functional_traits$X %in% FLK_fish$X,]
str(FLK_traits)
# Reorder species alphabetically
FLK_traits <- FLK_traits[order(row.names(FLK_traits)),]
# Trim off other taxonomic levels other than species name
FLKt <- FLK_traits[,-c(1:6)]
# FLKt$Location <- "FLK"
FLKt <- cbind(FLKt, env[3,])

# GLK
GLK_traits <- species_functional_traits[species_functional_traits$X %in% GLK_fish$X,]
str(GLK_traits)
# Reorder species alphabetically
GLK_traits <- GLK_traits[order(row.names(GLK_traits)),]
# Trim off other taxonomic levels other than species name
GLKt <- GLK_traits[,-c(1:6)]
# GLKt$Location <- "GLK"
GLKt <- cbind(GLKt, env[4,])

# HLM
HLM_traits <- species_functional_traits[species_functional_traits$X %in% HLM_fish$X,]
str(HLM_traits)
# Reorder species alphabetically
HLM_traits <- HLM_traits[order(row.names(HLM_traits)),]
# Trim off other taxonomic levels other than species name
HLMt <- HLM_traits[,-c(1:6)]
# HLMt$Location <- "HLM"
HLMt <- cbind(HLMt, env[5,])

# HLO
HLO_traits <- species_functional_traits[species_functional_traits$X %in% HLO_fish$X,]
str(HLO_traits)
# Reorder species alphabetically
HLO_traits <- HLO_traits[order(row.names(HLO_traits)),]
# Trim off other taxonomic levels other than species name
HLOt <- HLO_traits[,-c(1:6)]
# HLOt$Location <- "HLO"
HLOt <- cbind(HLOt, env[6,])

# IBK
IBK_traits <- species_functional_traits[species_functional_traits$X %in% IBK_fish$X,]
str(IBK_traits)
# Reorder species alphabetically
IBK_traits <- IBK_traits[order(row.names(IBK_traits)),]
# Trim off other taxonomic levels other than species name
IBKt <- IBK_traits[,-c(1:6)]
# IBKt$Location <- "IBK"
IBKt <- cbind(IBKt, env[7,])

# LLN
LLN_traits <- species_functional_traits[species_functional_traits$X %in% LLN_fish$X,]
str(LLN_traits)
# Reorder species alphabetically
LLN_traits <- LLN_traits[order(row.names(LLN_traits)),]
# Trim off other taxonomic levels other than species name
LLNt <- LLN_traits[,-c(1:6)]
# LLNt$Location <- "LLN"
LLNt <- cbind(LLNt, env[8,])

# LCN
LCN_traits <- species_functional_traits[species_functional_traits$X %in% LCN_fish$X,]
str(LCN_traits)
# Reorder species alphabetically
LCN_traits <- LCN_traits[order(row.names(LCN_traits)),]
# Trim off other taxonomic levels other than species name
LCNt <- LCN_traits[,-c(1:6)]
# LCNt$Location <- "LCN"
LCNt <- cbind(LCNt, env[9,])

# MLN
MLN_traits <- species_functional_traits[species_functional_traits$X %in% MLN_fish$X,]
str(MLN_traits)
# Reorder species alphabetically
MLN_traits <- MLN_traits[order(row.names(MLN_traits)),]
# Trim off other taxonomic levels other than species name
MLNt <- MLN_traits[,-c(1:6)]
# MLNt$Location <- "MLN"
MLNt <- cbind(MLNt, env[10,])

# NCN
NCN_traits <- species_functional_traits[species_functional_traits$X %in% NCN_fish$X,]
str(NCN_traits)
# Reorder species alphabetically
NCN_traits <- NCN_traits[order(row.names(NCN_traits)),]
# Trim off other taxonomic levels other than species name
NCNt <- NCN_traits[,-c(1:6)]
# NCNt$Location <- "NCN"
NCNt <- cbind(NCNt, env[11,])

# NLK
NLK_traits <- species_functional_traits[species_functional_traits$X %in% NLK_fish$X,]
str(NLK_traits)
# Reorder species alphabetically
NLK_traits <- NLK_traits[order(row.names(NLK_traits)),]
# Trim off other taxonomic levels other than species name
NLKt <- NLK_traits[,-c(1:6)]
# NLKt$Location <- "NLK"
NLKt <- cbind(NLKt, env[12,])

# NLN
NLN_traits <- species_functional_traits[species_functional_traits$X %in% NLN_fish$X,]
str(NLN_traits)
# Reorder species alphabetically
NLN_traits <- NLN_traits[order(row.names(NLN_traits)),]
# Trim off other taxonomic levels other than species name
NLNt <- NLN_traits[,-c(1:6)]
# NLNt$Location <- "NLN"
NLNt <- cbind(NLNt, env[13,])

# NLU
NLU_traits <- species_functional_traits[species_functional_traits$X %in% NLU_fish$X,]
str(NLU_traits)
# Reorder species alphabetically
NLU_traits <- NLU_traits[order(row.names(NLU_traits)),]
# Trim off other taxonomic levels other than species name
NLUt <- NLU_traits[,-c(1:6)]
# NLUt$Location <- "NLU"
NLUt <- cbind(NLUt, env[14,])

# OLO
OLO_traits <- species_functional_traits[species_functional_traits$X %in% OLO_fish$X,]
str(OLO_traits)
# Reorder species alphabetically
OLO_traits <- OLO_traits[order(row.names(OLO_traits)),]
# Trim off other taxonomic levels other than species name
OLOt <- OLO_traits[,-c(1:6)]
# OLOt$Location <- "OLO"
OLOt <- cbind(OLOt, env[15,])

# OCO
OCO_traits <- species_functional_traits[species_functional_traits$X %in% OCO_fish$X,]
str(OCO_traits)
# Reorder species alphabetically
OCO_traits <- OCO_traits[order(row.names(OCO_traits)),]
# Trim off other taxonomic levels other than species name
OCOt <- OCO_traits[,-c(1:6)]
# OCOt$Location <- "OCO"
OCOt <- cbind(OCOt, env[16,])

# OTM
OTM_traits <- species_functional_traits[species_functional_traits$X %in% OTM_fish$X,]
str(OTM_traits)
# Reorder species alphabetically
OTM_traits <- OTM_traits[order(row.names(OTM_traits)),]
# Trim off other taxonomic levels other than species name
OTMt <- OTM_traits[,-c(1:6)]
# OTMt$Location <- "OTM"
OTMt <- cbind(OTMt, env[17,])

# OCM
OCM_traits <- species_functional_traits[species_functional_traits$X %in% OCM_fish$X,]
str(OCM_traits)
# Reorder species alphabetically
OCM_traits <- OCM_traits[order(row.names(OCM_traits)),]
# Trim off other taxonomic levels other than species name
OCMt <- OCM_traits[,-c(1:6)]
# OCMt$Location <- "OCM"
OCMt <- cbind(OCMt, env[18,])

# RCA
RCA_traits <- species_functional_traits[species_functional_traits$X %in% RCA_fish$X,]
str(RCA_traits)
# Reorder species alphabetically
RCA_traits <- RCA_traits[order(row.names(RCA_traits)),]
# Trim off other taxonomic levels other than species name
RCAt <- RCA_traits[,-c(1:6)]
# RCAt$Location <- "RCA"
RCAt <- cbind(RCAt, env[19,])

# SLN
SLN_traits <- species_functional_traits[species_functional_traits$X %in% SLN_fish$X,]
str(SLN_traits)
# Reorder species alphabetically
SLN_traits <- SLN_traits[order(row.names(SLN_traits)),]
# Trim off other taxonomic levels other than species name
SLNt <- SLN_traits[,-c(1:6)]
# SLNt$Location <- "SLN"
SLNt <- cbind(SLNt, env[21,])

# TLN
TLN_traits <- species_functional_traits[species_functional_traits$X %in% TLN_fish$X,]
str(TLN_traits)
# Reorder species alphabetically
TLN_traits <- TLN_traits[order(row.names(TLN_traits)),]
# Trim off other taxonomic levels other than species name
TLNt <- TLN_traits[,-c(1:6)]
# TLNt$Location <- "TLN"
TLNt <- cbind(TLNt, env[22,])

# ULN
ULN_traits <- species_functional_traits[species_functional_traits$X %in% ULN_fish$X,]
str(ULN_traits)
# Reorder species alphabetically
ULN_traits <- ULN_traits[order(row.names(ULN_traits)),]
# Trim off other taxonomic levels other than species name
ULNt <- ULN_traits[,-c(1:6)]
# ULNt$Location <- "ULN"
ULNt <- cbind(ULNt, env[23,])

# All sites
Locations_at <- rbind(BCMt, CLMt, FLKt, GLKt, HLMt, HLOt, IBKt, LLNt, LCNt, MLNt, NCNt, NLKt, NLNt, NLUt, OLOt, OCOt, OTMt, OCMt, RCAt, SLNt, TLNt, ULNt)
# Rename column
Locations_at <- Locations_at %>%
  rename(Location = X)

# Calculate median and mode for columns by "Location"
Locations_at_summary <- Locations_at[1:16] %>%
  group_by(Location) %>%
  summarise(across(.cols = where(is.numeric), 
                .fns = list(median = median), 
                .names = "{.col}_{.fn}", 
                na.rm = TRUE),
         across(.cols = where(is.factor), 
                .fns = ~ names(which.max(table(.))), 
                .names = "{.col}_mode"))

Locations_at_summary <- cbind(Locations_at_summary,env[-20,-1])

row.names(Locations_at_summary) <- Locations_at_summary$Location

# Marine lakes
Lakes_at <- rbind(BCMt, CLMt, FLKt, GLKt, HLMt, HLOt, LLNt, MLNt, NLKt, NLNt, NLUt, OLOt, OTMt, SLNt, TLNt, ULNt)
# Rename column
Lakes_at <- Lakes_at %>%
  rename(Location = X)

Ocean_at <- rbind(IBKt, LCNt, NCNt, OCOt, OCMt, RCAt)
Mixed_at <- rbind(FLKt, HLOt, LLNt, MLNt, NLNt, NLUt, OLOt, ULNt)
Stratified_at <- rbind(BCMt, CLMt, GLKt, HLMt, NLKt, OTMt, SLNt, TLNt)
```

## Load out modified files
```{r, Bringing everything together load out modified files and session info}
# Environment
write.csv(env,"/Users/bailey/Documents/research/Fish_Biodiversity/data/collection/environment/env.csv")

# Fish presence by lake
write.csv(pres_abs_lake_sums,"/Users/bailey/Documents/research/Fish_Biodiversity/data/collection/fish/pres_abs/pres_abs_lake_sums.csv")

# Fish presence by species
write.csv(pres_abs_species_sums,"/Users/bailey/Documents/research/Fish_Biodiversity/data/collection/fish/pres_abs/pres_abs_species_sums.csv")

# Fish presence in surveyed sites by Location_type abundance
write.csv(surveyed_sites_strat_abund,"/Users/bailey/Documents/research/Fish_Biodiversity/data/collection/fish/pres_abs/surveyed_sites_strat_abund.csv")

# Fish presence in ocean sites
write.csv(ocean_site,"/Users/bailey/Documents/research/Fish_Biodiversity/data/collection/fish/pres_abs/ocean_site_presence_by_site.csv")

# Phylogenetic tree
write.tree(tree,"/Users/bailey/Documents/research/Fish_Biodiversity/data/collection/fish/phylo/fish_tree.tre")

# Phylogeny of surveyed sites
write.tree(stree,"/Users/bailey/Documents/research/Fish_Biodiversity/data/collection/fish/phylo/surveyed_fish_tree.tre")

# Phylogeny of sites with environmental data
write.tree(etree,"/Users/bailey/Documents/research/Fish_Biodiversity/data/collection/fish/phylo/env_fish_tree.tre")

# Phylogeny of sites with biogeographic data
write.tree(btree,"/Users/bailey/Documents/research/Fish_Biodiversity/data/collection/fish/phylo/biogeo_fish_tree.tre")

# Traits
write.csv(species_functional_traits,"/Users/bailey/Documents/research/Fish_Biodiversity/data/collection/fish/traits/traits.csv")

# Traits in surveyed sites
write.csv(surveyed_sites_traits,"/Users/bailey/Documents/research/Fish_Biodiversity/data/collection/fish/traits/surveyed_sites_traits.csv")

# Traits in ocean sites
write.csv(ocean_traits,"/Users/bailey/Documents/research/Fish_Biodiversity/data/collection/fish/traits/ocean_traits.csv")

sessionInfo()
```