---
title: "Palau lake environment"
output: github_document
editor_options: 
  chunk_output_type: console
---
#### R Markdown

## Load in packages
```{r}
library(dplyr)
```

## Load in and process files
- Bring the environmental data into R. Missing environment data from Long Lake and some of the ocean sites. We didn't sample fish occurrences from SLM or spooky lake. #From trait-beta-div-processing.R
```{r,}
####################################
##### -- Environmental data -- #####
####################################
##### -- Load data -- #####
env_data <- read.csv("/Users/bailey/Documents/research/fish_biodiversity/data/collection/environment/annual-environmental/annual-environmental-without_h2s_layer.csv", header = TRUE)

# Generate depth-by-lake environmental summaries
env_data_means <- env_data[, -c(2:4, 14)] %>%
  group_by(lake_code, depth) %>%
  summarise(across(.cols = everything(), ~mean(., na.rm = TRUE)))

# Generate summaries of environmental variables
environment_by_lake <- env_data_means %>%
  dplyr::select(-depth) %>%
  group_by(lake_code) %>%
  summarise(across(.cols = everything(), list(median = ~median(., na.rm = TRUE), sd = ~sd(., na.rm = TRUE)), .names = "{.col}_{.fn}"))

# depth <- env_data_means %>%
#   dplyr::select(lake_code, depth) %>%
#   group_by(lake_code) %>%
#   summarise(across(.cols = depth, .fns = mean, .names = NULL, na.rm = TRUE))
# 
# depth[depth == "NaN"] <- NA
# 
# environment_byLake <- merge(environment_by_lake, depth, by = "lake_code", all = TRUE)

## Add additional lakes attributes
# Add measures of area and isolation
lake_attributes <- read.csv("/Users/bailey/Documents/research/fish_biodiversity/data/collection/environment/lake_physical_attributes.csv", header = TRUE)

# Combine the physical and chemical factors for the lakes the by the site column
env_by_lake <- merge(environment_by_lake, lake_attributes, by = "lake_code", all = TRUE)

row.names(env_by_lake) <- env_by_lake$lake_code

env_by_lake <- env_by_lake[,-1]

# Reorder the columns based on the desired order
desired_order <- c("BCM", "CLM", "FLK", "GLK", "HLM", "HLO", "IBK", "LLN", "LCN", "MLN", "NCN", "NLK", "NLN", "NLU", "OLO", "OOO", "OTM", "OOM", "RCA", "REF", "SLN", "TLN", "ULN")
env_by_lake <- env_by_lake[desired_order,]
```

## Load out files
```{r, Load out env files and session info}
# Contains environmental data for lakes sample from
write.csv(env_by_lake, "/Users/bailey/Documents/research/fish_biodiversity/data/collection/environment/env_by_lake.csv")

sessionInfo()
```

