---
title: "FD analyses results"
output: github_document
editor_options: 
  chunk_output_type: console
---
#### R Markdown

## Load packages and files
```{r, FD analyses results load packages and files}
# Load the knitr package if not already loaded
library(knitr)

# Source the R Markdown file
knit("/Users/bailey/Documents/research/fish_biodiversity/src/collection/load_collection_data.Rmd", output = "/Users/bailey/Documents/research/fish_biodiversity/src/collection/load_collection_data.md")

library(dplyr)
library(tidyr)
library(ggplot2)
library(viridis)
library(ggrepel)

#Analyses
library(vegan)
library(FD)

surveyed_sites <- c("BCM", "CLM", "FLK", "GLK", "HLM", "HLO", "IBK", "LLN", "LCN", "MLN", "NCN", "NLK", "NLN", "NLU", "OLO", "OOO", "OTM", "OOM", "RCA", "SLN", "TLN", "ULN")

# Define your custom colors
custom_colors <- c("Reference" = "black", "Ocean" = "#EE6363", "Mixed" = "#87CEFA", "Stratified" = "#6E8B3D")
```

## Functional Diversity FRic, FEve, FDiv, FDis, CWM
```{r, Functional Diversity FRic, FEve, FDiv, FDis, CWM, eval = FALSE}
# All sites including reference
# Using categorical excludes variance eitehr by mode or meidan whereas turning them into numerical allows the use of the mean which provides greater population variation measurement but same general outcome
FD_total <- dbFD(traits, presabs_lake, w.abun = T, corr = "cailliez")
FRic_total <- FD_total$FRic
FEve_total <- FD_total$FEve
FDiv_total <- FD_total$FDiv
FDis_total <- FD_total$FDis
CWM_total <- FD_total$CWM
FD_total <- cbind(FRic_total, FEve_total, FDiv_total, FDis_total, CWM_total)

write.csv(FD_total, "/Users/bailey/Documents/research/fish_biodiversity/data/analyses/traits/FD_total.csv")

# All sites including reference but categorical traits are made numeric
ntraits <- traits

ntraits$BodyShapeI <- as.numeric(ntraits$BodyShapeI)
ntraits$DemersPelag <- as.numeric(ntraits$DemersPelag)
ntraits$OperculumPresent <- as.numeric(ntraits$OperculumPresent)
ntraits$FeedingPath <- as.numeric(ntraits$FeedingPath)
ntraits$RepGuild1 <- as.numeric(ntraits$RepGuild1)
ntraits$RepGuild2 <- as.numeric(ntraits$RepGuild2)
ntraits$ParentalCare <- as.numeric(ntraits$ParentalCare)
ntraits$WaterPref <- as.numeric(ntraits$WaterPref)

FD_total_an <- dbFD(ntraits, presabs_lake, w.abun = T, corr = "cailliez")
FRic_total_an <- FD_total_an$FRic
FEve_total_an <- FD_total_an$FEve
FDiv_total_an <- FD_total_an$FDiv
FDis_total_an <- FD_total_an$FDis
CWM_total_an <- FD_total_an$CWM
FD_total_an <- cbind(FRic_total_an, FEve_total_an, FDiv_total_an, FDis_total_an, CWM_total_an)

write.csv(FD_total_an, "/Users/bailey/Documents/research/fish_biodiversity/data/analyses/traits/FD_total_an.csv")

# Only surveyed sites
FD_sites <- dbFD(straits, surveyed_sites_lake, corr = "cailliez", calc.CWM = F)
# CWM_sites <- functcomp(straits, surveyed_sites_lake)
FRic_sites <- FD_sites$FRic
FEve_sites <- FD_sites$FEve
FDiv_sites <- FD_sites$FDiv
FDis_sites <- FD_sites$FDis
# CWM_sites <- FD_sites$CWM
FD_sites <- cbind(FRic_sites, FEve_sites, FDiv_sites, FDis_sites)

write.csv(FD_sites, "/Users/bailey/Documents/research/fish_biodiversity/data/analyses/traits/FD_sites.csv")

# Surveyed sites and community types without abundance
FD_total_strat <- dbFD(traits, strat_presabs_lake, corr = "cailliez")
# CWM_sites <- functcomp(straits, surveyed_sites_strat)
FRic_total_strat <- FD_total_strat$FRic
FEve_total_strat <- FD_total_strat$FEve
FDiv_total_strat <- FD_total_strat$FDiv
FDis_total_strat <- FD_total_strat$FDis
# CWM_total_strat <- FD_total_strat$CWM
FD_total_strat <- cbind(FRic_total_strat, FEve_total_strat, FDiv_total_strat, FDis_total_strat)

write.csv(FD_total_strat, "/Users/bailey/Documents/research/fish_biodiversity/data/analyses/traits/FD_total_strat.csv")

# Surveyed sites and community types with abundance in each
FD_sites_strat <- dbFD(straits, surveyed_sites_strat, w.abun = T, corr = "cailliez", calc.CWM = F)
# CWM_sites <- functcomp(straits, surveyed_sites_sites_strat)
FRic_sites_strat <- FD_sites_strat$FRic
FEve_sites_strat <- FD_sites_strat$FEve
FDiv_sites_strat <- FD_sites_strat$FDiv
FDis_sites_strat <- FD_sites_strat$FDis
# CWM_sites_strat <- FD_sites_strat$CWM
FD_sites_strat <- cbind(FRic_sites_strat, FEve_sites_strat, FDiv_sites_strat, FDis_sites_strat)

write.csv(FD_sites_strat, "/Users/bailey/Documents/research/fish_biodiversity/data/analyses/traits/FD_sites_strat.csv")
```

## Edit FD files
- Read in Functional Diversity file and combine with env data
```{r, Edit FD files}
FD_total <- read.csv("/Users/bailey/Documents/research/fish_biodiversity/data/analyses/traits/FD_total.csv")

FD_total_env <- merge(FD_total, env[,-c(33:47)], by = "X", sort = F)
FD_total_env$Community <- factor(FD_total_env$Community, levels = c("Reference", "Ocean", "Holomictic", "Meromictic"))
FD_total_env$Stratification <- factor(FD_total_env$Stratification, levels = c("Reference", "Ocean", "Mixed", "Stratified"))
row.names(FD_total_env) <- FD_total_env$X
FD_total_env$B <- FD_total_env$BodyShapeI
FD_total_env$O <- FD_total_env$OperculumPresent
FD_total_env$DS <- FD_total_env$DorsalSpinesMean
FD_total_env$L <- FD_total_env$MaxLengthTL
FD_total_env$T <- FD_total_env$Troph
FD_total_env$DMin <- FD_total_env$DepthMin
FD_total_env$DMax <- FD_total_env$DepthMax
FD_total_env$TMin <- FD_total_env$TempPrefMin
FD_total_env$TMax <- FD_total_env$TempPrefMax
FD_total_env$FP <- FD_total_env$FeedingPath
FD_total_env$EC <- FD_total_env$RepGuild1
FD_total_env$ES <- FD_total_env$RepGuild2
FD_total_env$P <- FD_total_env$ParentalCare
FD_total_env$W <- FD_total_env$WaterPref

FD_total_env_numerical <- FD_total_env[, c("DS", "L", "T", "DMin", "DMax", "TMin", "TMax")]
FD_total_env_numerical$X <- row.names(FD_total_env_numerical)

FD_total_env_categorical <- as.data.frame(model.matrix(~ B + O + FP + EC + ES + P + W, data = FD_total_env))
FD_total_env_categorical$X <- row.names(FD_total_env_categorical)

FD_total_env_for_scale <- full_join(FD_total_env_numerical, FD_total_env_categorical, by = "X")
row.names(FD_total_env_for_scale) <- FD_total_env_for_scale$X
FD_total_env_for_scale <- FD_total_env_for_scale[,-c(8:9)]

# Standardize the variables
scaled_FD_total_env <- as.data.frame(scale(FD_total_env_for_scale))


FD_total_n <- read.csv("/Users/bailey/Documents/research/fish_biodiversity/data/analyses/traits/FD_total_n.csv")

FD_total_n_env <- merge(FD_total_n, FD_total_env[,-c(2:20)], by = "X", sort = F)
row.names(FD_total_n) <- FD_total_n$X
row.names(FD_total_n_env) <- FD_total_n_env$X 


FD_total_sub <- read.csv("/Users/bailey/Documents/research/fish_biodiversity/data/analyses/traits/FD_total_sub.csv")

FD_total_sub_env <- merge(FD_total_sub, FD_total_env[,-c(2:5)], by = "X", sort = F)
FD_total_sub <- merge(FD_total_sub, FD_total[,-c(2:5)], by = "X", sort = F)
row.names(FD_total_sub) <- FD_total_sub$X
row.names(FD_total_sub_env) <- FD_total_sub_env$X 


FD_sites <- read.csv("/Users/bailey/Documents/research/fish_biodiversity/data/analyses/traits/FD_sites.csv")

FD_sites_env <- merge(FD_sites, FD_total_env[,-c(2:5)], by = "X", sort = F)
FD_sites <- merge(FD_sites, FD_total[,-c(2:5)], by = "X", sort = F)
row.names(FD_sites) <- FD_sites$X
row.names(FD_sites_env) <- FD_sites_env$X 


FD_total_strat <- read.csv("/Users/bailey/Documents/research/fish_biodiversity/data/analyses/traits/FD_total_strat.csv")


FD_sites_strat <- read.csv("/Users/bailey/Documents/research/fish_biodiversity/data/analyses/traits/FD_sites_strat.csv")
```

## Biplot of FRic and FDis
```{r, Biplot of FRic and FDis}
FRic_FDis_plot <- ggplot(data = FD_total_env, mapping = aes(y = FDis_total, x = FRic_total, color = Stratification, fill = Stratification)) + 
  geom_point(stat = 'identity',
    size = 4,
    alpha = 1, aes(group = Stratification, color = Stratification, fill = Stratification)) + 
  geom_text_repel(data = FD_total_env, label = FD_total_env$X, size = 5, point.padding = 3) +
  scale_color_manual(values = custom_colors) +
  scale_fill_manual(values = custom_colors) +
  theme_bw() +
  theme(text = element_text(size = 22), 
    legend.title = element_text(size = 16),  # Adjust legend title size
    legend.text = element_text(size = 16),  # Adjust legend text size
    axis.text = element_text(size = 22, color = "black"),
    axis.line = element_line(color = "black"),
    plot.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank()) +
  labs(x= "FRic", y= "FDisp", colour = "Site type", fill = "Site type")
  # ylim(c(0,1)) +
  # scale_x_continuous(breaks = c(-6, -4, -2, 0, 2), limits = c(-7,2)) +
  # annotate('rect', ymin=0, ymax=1, xmin=-2, xmax=2, alpha = 0.3, fill='grey')
FRic_FDis_plot <- FRic_FDis_plot + guides(color = guide_legend(override.aes = list(label = "")))
FRic_FDis_plot
ggsave("/Users/bailey/Documents/research/fish_biodiversity/figures/FD_plots/FRic_FDis_plot.png", FRic_FDis_plot, width = 6, height = 4, units = "in")
```

```{r, FD analyses results session info}
sessionInfo()
```

## Null models of functional diversity
```{r, Null models of functional diversity, eval = FALSE}
#Try to bootstrap or null model community weighted mean
null_sites <- lapply(1:1000, function(x){
  randomizeMatrix(surveyed_sites_lake, null.model = "trialswap")
})
  
FD_null_sites <- lapply(1:1000, function(x){
dbFD(straits, null_sites[[x]], w.abun = T, corr = "cailliez")
})


null_sums_abund <- lapply(1:1000, function(x){
  randomizeMatrix(surveyed_sites_strat_abund, null.model = "trialswap")
})
  
FD_null_sums_abund <- lapply(1:1000, function(x){
dbFD(straits, null_sums_abund[[x]], w.abun = T, corr = "cailliez")
})

#Reference included
null <- lapply(1:1000, function(x){
  randomizeMatrix(presabs_lake, null.model = "trialswap")
})
  
FD_null <- lapply(1:1000, function(x){
dbFD(traits, null[[x]], w.abun = T, corr = "cailliez")
})
```

## Community weighted mean
```{r, CWM with null, eval = FALSE}
#Extract CWM dataframe
CWM_sums_abund <- FD_sums_abund[,c(1,6:21)]

#Extract CWM_null from list
CWM_null_sums_abund <- lapply(1:1000, function(x){
as.data.frame(FD_null_sums_abund[[x]]$CWM)
})

CWM_null_sums_abund <- do.call("rbind", CWM_null_sums_abund)


CWM_null_sums_abund_nvalues <- apply(CWM_null_sums_abund, 1, function(x){
          c(null_mean = mean(x), null_sd = sd(x))})

CWM_null_sums_abund_nvalues <- lapply(CWM_null_sums_abund, function(x){
  c(unlist(c(apply(x[, -c(1,2,4,12:16)], 1, function(y){
    null_mean = mean(y)}))),
    unlist(c(apply(x[, -c(1,2,4,12:16)], 1, function(z){
    null_sd = sd(z)})))
)})

CWM_null_sums_abund_summary <- lapply(FD_CWM_null_sums_abund, function(x){
  c(
  unlist(c(
    sapply(x[, c(1,2,4,12:16)], function(y){
      out_y <- table(y)
      ifelse(length(out_y) > 0, names(which.max(out_y)), NA)
    }))),    
  apply(x[, -c(1,2,4,12:16)], 2, mean, na.rm=T)
    )
})  
  

CWM_null_sas <- data.frame(do.call("rbind", FD_CWM_null_sums_abund))

CWM_null_values <- t(CWM_null__sums_abund_values)

CWM_null_values <- as.data.frame(CWM_null_values)

CWM_null_values$lake_code <- row.names(CWM_null_values)

CWM <- merge(CWM, CWM_null_values, by = 'lake_code')

CWM$z_score <- ((CWM$observed_mean - CWM$null_mean)/CWM$null_sd)

row.names(CWM) <- CWM$lake_code

CWM <- CWM[,-1]

write.csv(CWM, "/Users/bailey/Documents/research/fish_biodiversity/data/analyses/traits/CWM.csv")
```

## Functional Richness
```{r, FRic with null, eval = FALSE}
#Extract FRic_sites dataframe
FRic_sites <- FD_sites[,c(1:2)]

#Extract FRic_sites_null from list
FRic_null_sites <- lapply(1:1000, function(x){
as.data.frame(FD_null_sites[[x]]$FRic)
})

FRic_null_sites <- do.call("cbind", FRic_null_sites)

FRic_null_sites_values <- apply(FRic_null_sites, 1, function(x){
  c(null_mean = mean(x), null_sd = sd(x))
})

FRic_null_sites_values <- as.data.frame(t(FRic_null_sites_values))

FRic_null_sites_values$X <- row.names(FRic_null_sites_values)

FRic_sites <- merge(FRic_sites, FRic_null_sites_values, by = 'X')

FRic_sites$z_score <- ((FRic_sites$FRic_sites - FRic_sites$null_mean)/FRic_sites$null_sd)

row.names(FRic_sites) <- FRic_sites$X

FRic_sites <- FRic_sites[,-1]

write.csv(FRic_sites, "/Users/bailey/Documents/research/fish_biodiversity/data/analyses/traits/FRic_sites.csv")
```

## Functional Dispersion
```{r, FDis with null, eval = FALSE}
#Extract FD_sites dataframe
FDis_sites <- FD_sites[,c(1,5)]

FDis_null_sites <- lapply(1:10, function(x){
as.data.frame(FD_null_sites[[x]]$FDis)
})

FDis_null_sites <- do.call("cbind", FDis_null_sites)

FDis_null_sites_values <- apply(FDis_null_sites, 1, function(x){
  c(null_mean = mean(x), null_sd = sd(x))
})

FDis_null_sites_values <- as.data.frame(t(FDis_null_sites_values))

FDis_null_sites_values$X <- row.names(FDis_null_sites_values)

FDis_sites <- merge(FDis_sites, FDis_null_sites_values, by = 'X')

FDis_sites$z_score <- ((FDis_sites$FDis_sites - FDis_sites$null_mean)/FDis_sites$null_sd)

row.names(FDis_sites) <- FDis_sites$X

FDis_sites <- FDis_sites[,-1]

write.csv(FDis_sites, "/Users/bailey/Documents/research/fish_biodiversity/data/analyses/FDis_sites.csv")
```
