---
title: "Stratification abundance weighted mean trait plots"
output: github_document
editor_options: 
  chunk_output_type: console
---
#### R Markdown

## Load packages
```{r, Load Stratification weighted mean trait plots packages}
library(dplyr)
library(ggplot2)
library(viridis)

# Load the knitr package if not already loaded
library(knitr)

# Source the R Markdown file
knit("/Users/bailey/Documents/research/fish_biodiversity/src/collection/load_collection_data.Rmd", output = "/Users/bailey/Documents/research/fish_biodiversity/src/collection/load_collection_data.md")

# Define your custom colors
custom_colors <- c("R" = "black", "O" = "#EE6363", "M" = "#87CEFA", "S" = "#6E8B3D")
```

## Trophic level
```{r, Trophic level}
Troph_plot_weighted <- ggplot(Stratification_at_weighted, mapping = aes(x= Strat, y= Troph, color = "black", fill = Strat)) +
  geom_violin(alpha = 0.6, draw_quantiles = c(0.25, 0.5, 0.75), linewidth = 0.75, aes(group = Strat, color = Strat, fill = Strat)) +
  scale_color_manual(values = custom_colors) +
  scale_fill_manual(values = custom_colors) +
  guides(fill = "none", color = "none") +
  geom_jitter(shape = 21,
            size = 2,
            alpha = 0.8,
            width = 0.1) +
  theme_bw() +
  theme(text = element_text(size = 22), legend.text = element_text(size = 16),
    axis.text = element_text(size = 22, color = "black"),
    axis.line = element_line(color = "black"),
    plot.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank()) + 
  ylab("Trophic Level") +
  xlab("Site type") +
  labs(colour = "Site type", fill = "Site type", tag = "A")
Troph_plot_weighted
ggsave("/Users/bailey/Documents/research/fish_biodiversity/figures/stratification_trait_plots/Troph_plot_weighted.png", Troph_plot_weighted, width = 6, height = 4, units = "in")


# Troph_plot <- ggplot(Stratification_at, mapping = aes(x= Strat, y= Troph, fill = Strat)) +
#   geom_violin(alpha = 0.75, draw_quantiles = c(0.25, 0.5, 0.75)) +
#   scale_fill_viridis(alpha = 0.5, end = 0.75, discrete = T, option = "G") +
#   geom_jitter(shape = 21,
#             size = 3,
#             alpha = 0.75,
#             width = 0.1) +
#   theme_bw() +
#   theme(
#     plot.background = element_blank(),
#     panel.grid.major = element_blank(),
#     panel.grid.minor = element_blank(),
#     panel.border = element_blank(),
#     axis.line = element_line(color = "black")) +
#   ylab("Troph")
# Troph_plot
```

## Body Shape
```{r, Body Shape}
Stratification_at_props_BodyShape <- Stratification_at %>%
  group_by(Strat, BodyShapeI) %>%
  summarise(count = sum(SiteSums)) %>%
  mutate(proportion = count/sum(count))

BodyShape_plot_weighted <- ggplot(Stratification_at_props_BodyShape, mapping = aes(x= Strat, y= proportion, color = "black", fill = Strat, shape = BodyShapeI)) + 
  geom_point(position = "identity", size = 6, aes(group = Strat, color = Strat, fill = Strat)) +
  geom_line(position = "identity", aes(group = BodyShapeI), linewidth = 0.75, linetype = "dotted") +
  scale_shape_manual(name = "Body Shape", values = c(11, 21:25), labels = c("1o" = "other", "2s" = "short deep", "3f" = "fusiform", "4e" = "elongated", "5l" = "eel-like")) +
  scale_color_manual(values = custom_colors) +
  scale_fill_manual(values = custom_colors) +
  theme_bw() +
  theme(
    text = element_text(size = 22),
    legend.title = element_text(size = 16),  # Adjust legend title size
    legend.text = element_text(size = 16),  # Adjust legend text size
    axis.text = element_text(size = 22, color = "black"),
    axis.line = element_line(color = "black"),
    plot.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank()
  ) +
  guides(colour = "none", fill = "none") + # Remove the legends for Site type
  ylim(c(0,0.6)) +
  ylab("Proportion") +
  xlab("Site type") +
  labs(colour = "Site type", fill = "Site type", tag = "B")
BodyShape_plot_weighted
ggsave("/Users/bailey/Documents/research/fish_biodiversity/figures/stratification_trait_plots/BodyShape_plot_weighted.png", BodyShape_plot_weighted, width = 6, height = 4, units = "in")


# BodyShape_plot_weighted <- ggplot(Stratification_at_props_BodyShape, aes(fill=Stratification, y=proportion, x=BodyShapeI)) + 
#   geom_bar(position='dodge', stStratification_at='identity') +
#   scale_fill_viridis(alpha = 1, begin = 0.3, end = .85, discrete = T, option = "G") +  
#   guides(fill = "none", color = "none") +
#   theme_bw() +
#   theme(text = element_text(size = 24),
#     plot.background = element_blank(),
#     panel.grid.major = element_blank(),
#     panel.grid.minor = element_blank(),
#     panel.border = element_blank(),
#     axis.line = element_line(color = "black")) +
#   ylab("Proportion") +
#   xlab("Body Shape")
# BodyShape_plot_weighted
# ggsave("/Users/bailey/Documents/research/fish_biodiversity/figures/stratification_trait_plots/BodyShape_plot_weightedbar.png", BodyShape_plot_weighted, width = 6, height = 4, units = "in")


# # Identify how many individuals have one of the trait factors for each Stratification
# BodyShape_counts <- table(Stratification_at$Stratification, row.names = Stratification_at$BodyShapeI)
# 
# # Divide each count by the total number of rows to find the proportion
# BodyShape_props <- BodyShape_counts/(rowSums(BodyShape_counts))
# BodyShape_props
# 
# BodyShape_props <- as.dStratification_ata.frame(BodyShape_props)
# 
# BodyShape_props$Var1 <- factor(BodyShape_props$Var1, levels = c("Reference", "Ocean", "Holomictic", "Meromictic"))
# 
# BodyShape_plot <- ggplot(BodyShape_props, mapping = aes(x= Var1, y= Freq, color = Var1, shape = row.names)) + 
#   geom_point(position = "identity", size = 5, aes(group = Var1)) +
#   scale_color_viridis(alpha = 0.5, end = 0.75, discrete = T, option = "G") +
#   theme_bw() +
#   theme(
#     plot.background = element_blank(),
#     panel.grid.major = element_blank(),
#     panel.grid.minor = element_blank(),
#     panel.border = element_blank(),
#     axis.line = element_line(color = "black")) +
#   ylab("Proportion") +
#   xlab("BodyShape")
# BodyShape_plot
```

## Dorsal Spines Mean
```{r, Dorsal Spines Mean}
DorsalSpinesMean_plot_weighted <- ggplot(Stratification_at_weighted, mapping = aes(x= Strat, y= DorsalSpinesMean, color = "black", fill = Strat)) +
  geom_violin(alpha = 0.5, draw_quantiles = c(0.25, 0.5, 0.75), linewidth = 0.75, aes(group = Strat, color = Strat, fill = Strat)) +
  scale_color_manual(values = custom_colors) +
  scale_fill_manual(values = custom_colors) +
  guides(fill = "none", color = "none") +
  geom_jitter(shape = 21,
            size = 2,
            alpha = 0.6,
            width = 0.1) +
  theme_bw() +
  theme(text = element_text(size = 22), legend.text = element_text(size = 16),
    axis.text = element_text(size = 22, color = "black"),
    axis.line = element_line(color = "black"),
    plot.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank()) + 
  ylab("Dorsal Spines") +
  xlab("Site type") +
  labs(colour = "Site type", fill = "Site type", tag = "C")
DorsalSpinesMean_plot_weighted
# Warning messages:
# 1: Removed 10 rows containing non-finite values (`stat_ydensity()`). 
# 2: Removed 10 rows containing missing values (`geom_point()`). 
# Twelve values with NA
ggsave("/Users/bailey/Documents/research/fish_biodiversity/figures/stratification_trait_plots/DorsalSpinesMean_plot_weighted.png", DorsalSpinesMean_plot_weighted, width = 6, height = 4, units = "in")


# DorsalSpinesMax_plot <- ggplot(Stratification_at, mapping = aes(x= Strat, y= DorsalSpinesMax, fill = Strat)) +
#   geom_violin(alpha = 0.75, draw_quantiles = c(0.25, 0.5, 0.75)) +
#   scale_fill_viridis(alpha = 0.5, end = 0.75, discrete = T, option = "G") +
#   geom_jitter(shape = 21,
#             size = 3,
#             alpha = 0.75,
#             width = 0.1) +
#   theme_bw() +
#   theme(
#     plot.background = element_blank(),
#     panel.grid.major = element_blank(),
#     panel.grid.minor = element_blank(),
#     panel.border = element_blank(),
#     axis.line = element_line(color = "black")) +
#   ylab("DorsalSpinesMax")
# DorsalSpinesMax_plot
```

## Parental Care
```{r, Parental Care}
Stratification_at_props_ParentalCare <- Stratification_at %>%
  group_by(Strat, ParentalCare) %>%
  summarise(count = sum(SiteSums)) %>%
  mutate(proportion = count/sum(count))

Stratification_at_props_ParentalCare <- na.omit(Stratification_at_props_ParentalCare)

ParentalCare_plot_weighted <- ggplot(Stratification_at_props_ParentalCare, mapping = aes(x= Strat, y= proportion, color = "black", fill = Strat, shape = ParentalCare)) + 
  geom_point(position = "identity", size = 6, aes(group = Strat, color = Strat, fill = Strat)) +
  geom_line(position = "identity", aes(group = ParentalCare), linewidth = 0.75, linetype = "dotted") +
  scale_shape_manual(name = "Parental Care", values = c(21:25), labels = c('4n' = 'none', '3p' = 'paternal', '2m' = 'maternal', '1b' = 'biparental')) +
  scale_color_manual(values = custom_colors) +
  scale_fill_manual(values = custom_colors) +
  theme_bw() +
  theme(
    text = element_text(size = 22),
    legend.title = element_text(size = 16),  # Adjust legend title size
    legend.text = element_text(size = 16),  # Adjust legend text size
    axis.text = element_text(size = 22, color = "black"),
    axis.line = element_line(color = "black"),
    plot.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank()
  ) +
  guides(colour = "none", fill = "none") + # Remove the legends for Site type
  ylim(c(0,0.6)) +
  ylab("Proportion") +
  xlab("Site type") +
  labs(colour = "Site type", fill = "Site type", tag = "D")
ParentalCare_plot_weighted
ggsave("/Users/bailey/Documents/research/fish_biodiversity/figures/stratification_trait_plots/ParentalCare_plot_weighted.png", ParentalCare_plot_weighted, width = 6, height = 4, units = "in")


# # Identify how many individuals have one of the trait factors for each Stratification
# ParentalCare_counts <- table(Stratification_at$Stratification, row.names = Stratification_at$ParentalCare)
# 
# # Divide each count by the total number of rows to find the proportion
# ParentalCare_props <- ParentalCare_counts/(rowSums(ParentalCare_counts))
# ParentalCare_props
# 
# ParentalCare_props <- as.dStratification_ata.frame(ParentalCare_props)
# 
# ParentalCare_props$Var1 <- factor(ParentalCare_props$Var1, levels = c("Reference", "Ocean", "Holomictic", "Meromictic"))
# 
# ParentalCare_plot <- ggplot(ParentalCare_props, mapping = aes(x= Var1, y= Freq, color = Var1, shape = row.names)) + 
#   geom_point(position = "identity", size = 5, aes(group = Var1)) +
#   scale_color_viridis(alpha = 0.5, end = 0.75, discrete = T, option = "G") +
#   theme_bw() +
#   theme(
#     plot.background = element_blank(),
#     panel.grid.major = element_blank(),
#     panel.grid.minor = element_blank(),
#     panel.border = element_blank(),
#     axis.line = element_line(color = "black")) +
#   ylab("Proportion") +
#   xlab("Site type")
# ParentalCare_plot
```

## Depth Minimum
```{r, Depth Minimum}
DepthMin_plot_weighted <- ggplot(Stratification_at_weighted, mapping = aes(x= Strat, y= DepthMin, color = "black", fill = Strat)) +
  geom_violin(alpha = 0.5, draw_quantiles = c(0.25, 0.5, 0.75), linewidth = 0.75, aes(group = Strat, color = Strat, fill = Strat)) +
  scale_color_manual(values = custom_colors) +
  scale_fill_manual(values = custom_colors) +
  guides(fill = "none", color = "none") +
  geom_jitter(shape = 21,
            size = 2,
            alpha = 0.6,
            width = 0.1) +
  theme_bw() +
  theme(text = element_text(size = 22), legend.text = element_text(size = 16),
    axis.text = element_text(size = 22, color = "black"),
    axis.line = element_line(color = "black"),
    plot.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank()) + 
  ylim(c(-1,201)) +
  ylab("Depth Min (m)") +
  xlab("Site type") +
  labs(colour = "Site type", fill = "Site type", tag = "A")
DepthMin_plot_weighted
# Warning messages:
# 1: Removed 8 rows containing non-finite values (`stat_ydensity()`). 
# 2: Removed 8 rows containing missing values (`geom_point()`). 
# One value with NA
ggsave("/Users/bailey/Documents/research/fish_biodiversity/figures/stratification_trait_plots/DepthMin_plot_weighted.png", DepthMin_plot_weighted, width = 6, height = 4, units = "in")


# DepthMin_plot <- ggplot(Stratification_at, mapping = aes(x= Strat, y= DepthMin, fill = Strat)) +
#   geom_violin(alpha = 0.75, draw_quantiles = c(0.25, 0.5, 0.75)) +
#   scale_fill_viridis(alpha = 0.5, end = 0.75, discrete = T, option = "G") +
#   geom_jitter(shape = 21,
#             size = 3,
#             alpha = 0.75,
#             width = 0.1) +
#   theme_bw() +
#   theme(
#     plot.background = element_blank(),
#     panel.grid.major = element_blank(),
#     panel.grid.minor = element_blank(),
#     panel.border = element_blank(),
#     axis.line = element_line(color = "black")) +
#   ylab("DepthMin")
# DepthMin_plot
```

## Water
- Fresh/Brack/Salt
```{r, Water}
Stratification_at_props_Water <- Stratification_at %>%
  group_by(Strat, WaterPref) %>%
  summarise(count = sum(SiteSums)) %>%
  mutate(proportion = count/sum(count))

#Stratification_at_props_Water$Water <- factor(Stratification_at_props_Water$Water, levels = c("all", "fresh", "fresh-brack", "brack", "brack-salt", "salt"))

Water_plot_weighted <- ggplot(Stratification_at_props_Water, mapping = aes(x= Strat, y= proportion, color = "black", fill = Strat, shape = WaterPref)) + 
  geom_point(position = "identity", size = 6, aes(group = Strat, color = Strat, fill = Strat)) +
  geom_line(position = "identity", aes(group = WaterPref), linewidth = 0.75, linetype = "dotted") +
  scale_shape_manual(name = "Water", values = c(21:23,11,24:25), labels = c('3a' = 'all', '1s' = 'salt', '2bs' = 'brackish-salt', '4b' = 'brack', '5fb' = 'fresh-brackish', '6f' = 'fresh')) + 
  scale_color_manual(values = custom_colors) +
  scale_fill_manual(values = custom_colors) +
  theme_bw() +
  theme(
    text = element_text(size = 22),
    legend.title = element_text(size = 16),  # Adjust legend title size
    legend.text = element_text(size = 16),  # Adjust legend text size
    axis.text = element_text(size = 22, color = "black"),
    axis.line = element_line(color = "black"),
    plot.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank()
  ) +
  guides(colour = "none", fill = "none") + # Remove the legends for Site type
  ylim(c(0,1)) +
  ylab("Proportion") +
  xlab("Site type") +
  labs(colour = "Site type", fill = "Site type", tag = "B")
Water_plot_weighted
ggsave("/Users/bailey/Documents/research/fish_biodiversity/figures/stratification_trait_plots/Water_plot_weighted.png", Water_plot_weighted, width = 6, height = 4, units = "in")


# # Identify how many individuals have one of the trait factors for each Stratification
# Habitat_counts <- table(Stratification_at$Stratification, row.names = Stratification_at$Habitat)
# 
# # Divide each count by the total number of rows to find the proportion
# Habitat_props <- Habitat_counts/(rowSums(Habitat_counts))
# Habitat_props
# 
# Habitat_props <- as.dStratification_ata.frame(Habitat_props)
# 
# Habitat_props$Var1 <- factor(Habitat_props$Var1, levels = c("Reference", "Ocean", "Holomictic", "Meromictic"))
# 
# Habitat_plot <- ggplot(Habitat_props, mapping = aes(x= Var1, y= Freq, color = Var1, shape = row.names)) + 
#   geom_point(position = "identity", size = 5, aes(group = Var1)) +
#   scale_color_viridis(alpha = 0.5, end = 0.75, discrete = T, option = "G") +
#   theme_bw() +
#   theme(
#     plot.background = element_blank(),
#     panel.grid.major = element_blank(),
#     panel.grid.minor = element_blank(),
#     panel.border = element_blank(),
#     axis.line = element_line(color = "black")) +
#   ylab("Proportion") +
#   xlab("Habitat")
# Habitat_plot
```

## Max Length (TL)
```{r, Max Length (TL)}
MaxLengthTL_plot_weighted <- ggplot(Stratification_at_weighted, mapping = aes(x= Strat, y= MaxLengthTL, color = "black", fill = Strat)) +
  geom_violin(alpha = 0.5, draw_quantiles = c(0.25, 0.5, 0.75), linewidth = 0.75, aes(group = Strat, color = Strat, fill = Strat)) +
  scale_color_manual(values = custom_colors) +
  scale_fill_manual(values = custom_colors) +
  guides(fill = "none", color = "none") +
  geom_jitter(shape = 21,
            size = 2,
            alpha = 0.6,
            width = 0.1) +
  theme_bw() +
  theme(text = element_text(size = 22), legend.text = element_text(size = 16),
    axis.text = element_text(size = 22, color = "black"),
    axis.line = element_line(color = "black"),
    plot.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank()) + 
  ylim(c(0,450)) +
  ylab("Length (cm)") +
  xlab("Site type") +
  labs(colour = "Site type", fill = "Site type", tag = "B")
MaxLengthTL_plot_weighted
# Warning messages:
# 1: Removed 3 rows containing non-finite values (`stat_ydensity()`). 
# 2: Removed 3 rows containing missing values (`geom_point()`). 
ggsave("/Users/bailey/Documents/research/fish_biodiversity/figures/stratification_trait_plots/MaxLengthTL_plot_weighted.png", MaxLengthTL_plot_weighted, width = 6, height = 4, units = "in")


# MaxLengthTL_plot <- ggplot(Stratification_at, mapping = aes(x= Strat, y= MaxLengthTL, fill = Strat)) +
#   geom_violin(alpha = 0.75, draw_quantiles = c(0.25, 0.5, 0.75)) +
#   scale_fill_viridis(alpha = 0.5, end = 0.75, discrete = T, option = "G") +
#   geom_jitter(shape = 21,
#             size = 3,
#             alpha = 0.75,
#             width = 0.1) +
#   theme_bw() +
#   theme(
#     plot.background = element_blank(),
#     panel.grid.major = element_blank(),
#     panel.grid.minor = element_blank(),
#     panel.border = element_blank(),
#     axis.line = element_line(color = "black")) +
#   ylab("MaxLengthTL")
# MaxLengthTL_plot
```

## Operculum Present
```{r, Operculum Present}
Stratification_at_props_OperculumPresent <- Stratification_at %>%
  group_by(Strat, OperculumPresent) %>%
  summarise(count = sum(SiteSums)) %>%
  mutate(proportion = count/sum(count))

OperculumPresent_plot_weighted <- ggplot(Stratification_at_props_OperculumPresent, mapping = aes(x= Strat, y= proportion, color = "black", fill = Strat, shape = OperculumPresent)) + 
  geom_point(position = "identity", size = 6, aes(group = Strat, color = Strat, fill = Strat)) +
  geom_line(position = "identity", aes(group = OperculumPresent), linewidth = 0.75, linetype = "dotted") +
  scale_shape_manual(name = "Operculum", values = c(21:22)) +
  scale_color_manual(values = custom_colors) +
  scale_fill_manual(values = custom_colors) +
  theme_bw() +
  theme(
    text = element_text(size = 22),
    legend.title = element_text(size = 16),  # Adjust legend title size
    legend.text = element_text(size = 16),  # Adjust legend text size
    axis.text = element_text(size = 22, color = "black"),
    axis.line = element_line(color = "black"),
    plot.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank()
  ) +
  guides(colour = "none", fill = "none") + # Remove the legends for Site type
  ylim(c(0,0.75)) +
  ylab("Proportion") +
  xlab("Site type") +
  labs(colour = "Site type", fill = "Site type", tag = "A")
OperculumPresent_plot_weighted
ggsave("/Users/bailey/Documents/research/fish_biodiversity/figures/stratification_trait_plots/OperculumPresent_plot_weighted.png", OperculumPresent_plot_weighted, width = 6, height = 4, units = "in")


# # Identify how many individuals have one of the trait factors for each Stratification
# OperculumPresent_counts <- table(Stratification_at$Stratification, row.names = Stratification_at$OperculumPresent)
# 
# # Divide each count by the total number of rows to find the proportion
# OperculumPresent_props <- OperculumPresent_counts/(rowSums(OperculumPresent_counts))
# OperculumPresent_props
# 
# OperculumPresent_props <- as.dStratification_ata.frame(OperculumPresent_props)
# 
# OperculumPresent_props$Var1 <- factor(OperculumPresent_props$Var1, levels = c("Reference", "Ocean", "Holomictic", "Meromictic"))
# 
# OperculumPresent_plot <- ggplot(OperculumPresent_props, mapping = aes(x= Var1, y= Freq, color = Var1, shape = row.names)) + 
#   geom_point(position = "identity", size = 5, aes(group = Var1)) +
#   scale_color_viridis(alpha = 0.5, end = 0.75, discrete = T, option = "G") +
#   theme_bw() +
#   theme(
#     plot.background = element_blank(),
#     panel.grid.major = element_blank(),
#     panel.grid.minor = element_blank(),
#     panel.border = element_blank(),
#     axis.line = element_line(color = "black")) +
#   ylab("Proportion") +
#   xlab("OperculumPresent")
# OperculumPresent_plot
```

## Depth Maximum
```{r, Depth Maximum}
DepthMax_plot_weighted <- ggplot(Stratification_at_weighted, mapping = aes(x= Strat, y= DepthMax, color = "black", fill = Strat)) +
  geom_violin(alpha = 0.5, draw_quantiles = c(0.25, 0.5, 0.75), linewidth = 0.75, aes(group = Strat, color = Strat, fill = Strat)) +
  scale_color_manual(values = custom_colors) +
  scale_fill_manual(values = custom_colors) +
  guides(fill = "none", color = "none") +
  geom_jitter(shape = 21,
            size = 2,
            alpha = 0.6,
            width = 0.1) +
  theme_bw() +
  theme(text = element_text(size = 22), legend.text = element_text(size = 16),
    axis.text = element_text(size = 22, color = "black"),
    axis.line = element_line(color = "black"),
    plot.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank()) + 
  ylim(c(-1,1001)) +
  ylab("Depth Max (m)") +
  xlab("Site type") +
  labs(colour = "Site type", fill = "Site type", tag = "D")
DepthMax_plot_weighted
# Warning messages:
# 1: Removed 10 rows containing non-finite values (`stat_ydensity()`). 
# 2: Removed 10 rows containing missing values (`geom_point()`). 
# One value with NA
ggsave("/Users/bailey/Documents/research/fish_biodiversity/figures/stratification_trait_plots/DepthMax_plot_weighted.png", DepthMax_plot_weighted, width = 6, height = 4, units = "in")


# DepthMax_plot <- ggplot(Stratification_at, mapping = aes(x= Strat, y= DepthMax, fill = Strat)) +
#   geom_violin(alpha = 0.75, draw_quantiles = c(0.25, 0.5, 0.75)) +
#   scale_fill_viridis(alpha = 0.5, end = 0.75, discrete = T, option = "G") +
#   geom_jitter(shape = 21,
#             size = 3,
#             alpha = 0.75,
#             width = 0.1) +
#   theme_bw() +
#   theme(
#     plot.background = element_blank(),
#     panel.grid.major = element_blank(),
#     panel.grid.minor = element_blank(),
#     panel.border = element_blank(),
#     axis.line = element_line(color = "black")) +
#   ylab("DepthMax")
# DepthMax_plot
```

## Temperature Preference Minimum
```{r, Temperature Preference Minimum}
TempPrefMin_plot_weighted <- ggplot(Stratification_at_weighted, mapping = aes(x= Strat, y= TempPrefMin, color = "black", fill = Strat)) +
  geom_violin(alpha = 0.5, draw_quantiles = c(0.25, 0.5, 0.75), linewidth = 0.75, aes(group = Strat, color = Strat, fill = Strat)) +
  scale_color_manual(values = custom_colors) +
  scale_fill_manual(values = custom_colors) +
  guides(fill = "none", color = "none") +
  geom_jitter(shape = 21,
            size = 2,
            alpha = 0.6,
            width = 0.1) +
  theme_bw() +
  theme(text = element_text(size = 22), legend.text = element_text(size = 16),
    axis.text = element_text(size = 22, color = "black"),
    axis.line = element_line(color = "black"),
    plot.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank()) + 
  ylab("Temp Min (Cº)") +
  xlab("Site type") +
  labs(colour = "Site type", fill = "Site type", tag = "F")
TempPrefMin_plot_weighted
# Warning messages:
# 1: Removed 9 rows containing non-finite values (`stat_ydensity()`). 
# 2: Removed 9 rows containing missing values (`geom_point()`). 
# Two values with NA
ggsave("/Users/bailey/Documents/research/fish_biodiversity/figures/stratification_trait_plots/TempPrefMin_plot_weighted.png", TempPrefMin_plot_weighted, width = 6, height = 4, units = "in")


# TempPrefMin_plot <- ggplot(Stratification_at, mapping = aes(x= Strat, y= TempPrefMin, fill = Strat)) +
#   geom_violin(alpha = 0.75, draw_quantiles = c(0.25, 0.5, 0.75)) +
#   scale_fill_viridis(alpha = 0.5, end = 0.75, discrete = T, option = "G") +
#   geom_jitter(shape = 21,
#             size = 3,
#             alpha = 0.75,
#             width = 0.1) +
#   theme_bw() +
#   theme(
#     plot.background = element_blank(),
#     panel.grid.major = element_blank(),
#     panel.grid.minor = element_blank(),
#     panel.border = element_blank(),
#     axis.line = element_line(color = "black")) +
#   ylab("TempPrefMin")
# TempPrefMin_plot
```

## Temperature Preference Maximum
```{r, Temperature Preference Maximum}
TempPrefMax_plot_weighted <- ggplot(Stratification_at_weighted, mapping = aes(x= Strat, y= TempPrefMax, color = "black", fill = Strat)) +
  geom_violin(alpha = 0.5, draw_quantiles = c(0.25, 0.5, 0.75), linewidth = 0.75, aes(group = Strat, color = Strat, fill = Strat)) +
  scale_color_manual(values = custom_colors) +
  scale_fill_manual(values = custom_colors) +
  guides(fill = "none", color = "none") +
  geom_jitter(shape = 21,
            size = 2,
            alpha = 0.6,
            width = 0.1) +
  theme_bw() +
  theme(text = element_text(size = 22), legend.text = element_text(size = 16),
    axis.text = element_text(size = 22, color = "black"),
    axis.line = element_line(color = "black"),
    plot.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank()) + 
  ylim(c(17.5,30)) +
  ylab("Temp Max (Cº)") +
  xlab("Site type") +
  labs(colour = "Site type", fill = "Site type", tag = "H")
TempPrefMax_plot_weighted
# Warning messages:
# 1: Removed 11 rows containing non-finite values (`stat_ydensity()`). 
# 2: Removed 11 rows containing missing values (`geom_point()`). 
# Two values with NA
ggsave("/Users/bailey/Documents/research/fish_biodiversity/figures/stratification_trait_plots/TempPrefMax_plot_weighted.png", TempPrefMax_plot_weighted, width = 6, height = 4, units = "in")


# TempPrefMax_plot <- ggplot(Stratification_at, mapping = aes(x= Strat, y= TempPrefMax, fill = Strat)) +
#   geom_violin(alpha = 0.75, draw_quantiles = c(0.25, 0.5, 0.75)) +
#   scale_fill_viridis(alpha = 0.5, end = 0.75, discrete = T, option = "G") +
#   geom_jitter(shape = 21,
#             size = 3,
#             alpha = 0.75,
#             width = 0.1) +
#   theme_bw() +
#   theme(
#     plot.background = element_blank(),
#     panel.grid.major = element_blank(),
#     panel.grid.minor = element_blank(),
#     panel.border = element_blank(),
#     axis.line = element_line(color = "black")) +
#   ylab("TempPrefMax")
# TempPrefMax_plot
```

## Reproductive Guild1
```{r, Reproductive Guild1}
Stratification_at_props_RepGuild1 <- Stratification_at %>%
  group_by(Strat, RepGuild1) %>%
  summarise(count = sum(SiteSums)) %>%
  group_by(Strat) %>%
  mutate(proportion = count/sum(count))

Stratification_at_props_RepGuild1 <- na.omit(Stratification_at_props_RepGuild1)

RepGuild1_plot_weighted <- ggplot(Stratification_at_props_RepGuild1, mapping = aes(x = Strat, y = proportion, shape = RepGuild1)) + 
  geom_point(position = "identity", size = 6, aes(group = Strat, color = Strat, fill = Strat)) +
  geom_line(position = "identity", aes(group = RepGuild1), linewidth = 0.75, linetype = "dotted") +
  scale_shape_manual(name = "Egg Care", values = c(21, 22, 23), labels = c('2g' = 'guarders', '1b' = 'bearers', '3n' = 'nonguarders')) +
  scale_color_manual(values = custom_colors) +
  scale_fill_manual(values = custom_colors) +
  theme_bw() +
  theme(
    text = element_text(size = 22),
    legend.title = element_text(size = 16),  # Adjust legend title size
    legend.text = element_text(size = 16),  # Adjust legend text size
    axis.text = element_text(size = 22, color = "black"),
    axis.line = element_line(color = "black"),
    plot.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank()
  ) +
  guides(colour = "none", fill = "none") + # Remove the legends for Site type
  ylim(c(0, 0.6)) +
  ylab("Proportion") +
  xlab("Site type") +
  labs(tag = "C")

RepGuild1_plot_weighted
ggsave("/Users/bailey/Documents/research/fish_biodiversity/figures/stratification_trait_plots/RepGuild1_plot_weighted.png", RepGuild1_plot_weighted, width = 6, height = 4, units = "in")


# # Identify how many individuals have one of the trait factors for each Stratification
# RepGuild1_counts <- table(Stratification_at$Stratification, row.names = Stratification_at$RepGuild1)
# 
# # Divide each count by the total number of rows to find the proportion
# RepGuild1_props <- RepGuild1_counts/(rowSums(RepGuild1_counts))
# RepGuild1_props
# 
# RepGuild1_props <- as.dStratification_ata.frame(RepGuild1_props)
# 
# RepGuild1_props$Var1 <- factor(RepGuild1_props$Var1, levels = c("Reference", "Ocean", "Holomictic", "Meromictic"))
# 
# RepGuild1_plot <- ggplot(RepGuild1_props, mapping = aes(x= Var1, y= Freq, color = Var1, shape = row.names)) + 
#   geom_point(position = "identity", size = 5, aes(group = Var1)) +
#   scale_color_viridis(alpha = 0.5, end = 0.75, discrete = T, option = "G") +
#   theme_bw() +
#   theme(
#     plot.background = element_blank(),
#     panel.grid.major = element_blank(),
#     panel.grid.minor = element_blank(),
#     panel.border = element_blank(),
#     axis.line = element_line(color = "black")) +
#   ylab("Proportion") +
#   xlab("Site type")
# RepGuild1_plot
```

## Reproductive Guild2
```{r, Reproductive Guild2}
Stratification_at_props_RepGuild2 <- Stratification_at %>%
  group_by(Strat, RepGuild2) %>%
  summarise(count = sum(SiteSums)) %>%
  mutate(proportion = count/sum(count))

Stratification_at_props_RepGuild2 <- na.omit(Stratification_at_props_RepGuild2)

RepGuild2_plot_weighted <- ggplot(Stratification_at_props_RepGuild2, mapping = aes(x= Strat, y= proportion, color = "black", fill = Strat, shape = RepGuild2)) + 
  geom_point(position = "identity", size = 6, aes(group = Strat, color = Strat, fill = Strat)) +
  geom_line(position = "identity", aes(group = RepGuild2), linewidth = 0.75, linetype = "dotted") +
  scale_shape_manual(name = "Egg Strategy", values = c(11, 21:25), labels = c('1ib' = 'live bearers', '6s' = 'egg scatterers', '3n' = 'nesters', '5h' = 'brood hiders', '4t' = 'clutch tenders', '2eb' = 'external brooders')) +
  scale_color_manual(values = custom_colors) +
  scale_fill_manual(values = custom_colors) +
  theme_bw() +
  theme(
    text = element_text(size = 22),
    legend.title = element_text(size = 16),  # Adjust legend title size
    legend.text = element_text(size = 16),  # Adjust legend text size
    axis.text = element_text(size = 22, color = "black"),
    axis.line = element_line(color = "black"),
    plot.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank()
  ) +
  guides(colour = "none", fill = "none") + # Remove the legends for Site type
  ylim(c(0,0.6)) +
  ylab("Proportion") +
  xlab("Site type") +
  labs(colour = "Site type", fill = "Site type", tag = "E")
RepGuild2_plot_weighted
ggsave("/Users/bailey/Documents/research/fish_biodiversity/figures/stratification_trait_plots/RepGuild2_plot_weighted.png", RepGuild2_plot_weighted, width = 6, height = 4, units = "in")


# # Identify how many individuals have one of the trait factors for each Stratification
# RepGuild2_counts <- table(Stratification_at$Stratification, row.names = Stratification_at$RepGuild2)
# 
# # Divide each count by the total number of rows to find the proportion
# RepGuild2_props <- RepGuild2_counts/(rowSums(RepGuild2_counts))
# RepGuild2_props
# 
# RepGuild2_props <- as.dStratification_ata.frame(RepGuild2_props)
# 
# RepGuild2_props$Var1 <- factor(RepGuild2_props$Var1, levels = c("Reference", "Ocean", "Holomictic", "Meromictic"))
# 
# RepGuild2_plot <- ggplot(RepGuild2_props, mapping = aes(x= Var1, y= Freq, color = Var1, shape = row.names)) + 
#   geom_point(position = "identity", size = 5, aes(group = Var1)) +
#   scale_color_viridis(alpha = 0.5, end = 0.75, discrete = T, option = "G") +
#   theme_bw() +
#   theme(
#     plot.background = element_blank(),
#     panel.grid.major = element_blank(),
#     panel.grid.minor = element_blank(),
#     panel.border = element_blank(),
#     axis.line = element_line(color = "black")) +
#   ylab("Proportion") +
#   xlab("Site type")
# RepGuild2_plot
```

## DemersPelag
```{r, DemersPelag}
Stratification_at_props_DemersPelag <- Stratification_at %>%
  group_by(Strat, DemersPelag) %>%
  summarise(count = sum(SiteSums)) %>%
  mutate(proportion = count/sum(count))

DemersPelag_plot_weighted <- ggplot(Stratification_at_props_DemersPelag, mapping = aes(x= Strat, y= proportion, color = "black", fill = Strat, shape = DemersPelag)) + 
  geom_point(position = "identity", size = 6, aes(group = Strat, color = Strat, fill = Strat)) +
  geom_line(position = "identity", aes(group = DemersPelag), linewidth = 0.75, linetype = "dotted") +
  scale_shape_manual(name = "Demersal Pelagic", values = c(21:25, 12:13), 
                     labels = c("1r" = "reef-associated", "2pn" = "pelagic-neritic", "3p" = "pelagic", "4po" = "pelagic-oceanic", "5d" = "demersal", '6bp' = 'benthopelagic', '7bd' = 'bathydemersal')) +
  scale_color_manual(values = custom_colors) +
  scale_fill_manual(values = custom_colors) +
  theme_bw() +
  theme(
    text = element_text(size = 22),
    legend.title = element_text(size = 16),  # Adjust legend title size
    legend.text = element_text(size = 16),  # Adjust legend text size
    axis.text = element_text(size = 22, color = "black"),
    axis.line = element_line(color = "black"),
    plot.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank()
  ) +
  guides(colour = "none", fill = "none") + # Remove the legends for Site type
  ylim(c(0,1)) +
  ylab("Proportion") +
  xlab("Site type") +
  labs(colour = "Site type", fill = "Site type", tag = "G")
DemersPelag_plot_weighted
ggsave("/Users/bailey/Documents/research/fish_biodiversity/figures/stratification_trait_plots/DemersPelag_plot_weighted.png", DemersPelag_plot_weighted, width = 6, height = 4, units = "in")
```

## Feeding Pathway
```{r, Feeding Pathway}
Stratification_at_props_FeedingPath <- Stratification_at %>%
  group_by(Strat, FeedingPath) %>%
  summarise(count = sum(SiteSums)) %>%
  mutate(proportion = count/sum(count))

Stratification_at_props_FeedingPath <- na.omit(Stratification_at_props_FeedingPath)

FeedingPath_plot_weighted <- ggplot(Stratification_at_props_FeedingPath, mapping = aes(x= Strat, y= proportion, color = "black", fill = Strat, shape = FeedingPath)) + 
  geom_point(position = "identity", size = 6, aes(group = Strat, color = Strat, fill = Strat)) +
  geom_line(position = "identity", aes(group = FeedingPath), linewidth = 0.75, linetype = "dotted") +
  scale_shape_manual(name = "Diet Source", values = c(21:22), labels = c("b" = "benthic", "p" = "pelagic")) +
  scale_color_manual(values = custom_colors) +
  scale_fill_manual(values = custom_colors) +
  theme_bw() +
  theme(
    text = element_text(size = 22),
    legend.title = element_text(size = 16),  # Adjust legend title size
    legend.text = element_text(size = 16),  # Adjust legend text size
    axis.text = element_text(size = 22, color = "black"),
    axis.line = element_line(color = "black"),
    plot.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank()
  ) +
  guides(colour = "none", fill = "none") + # Remove the legends for Site type
  ylim(c(0,1)) +
  ylab("Proportion") +
  xlab("Site type") +
  labs(colour = "Site type", fill = "Site type", tag = "I")
FeedingPath_plot_weighted
ggsave("/Users/bailey/Documents/research/fish_biodiversity/figures/stratification_trait_plots/FeedingPath_plot_weighted.png", FeedingPath_plot_weighted, width = 6, height = 4, units = "in")


# # Identify how many individuals have one of the trait factors for each Stratification
# FeedingPath_counts <- table(Stratification_at$Stratification, row.names = Stratification_at$FeedingPStratification_ath)
# 
# # Divide each count by the total number of rows to find the proportion
# FeedingPath_props <- FeedingPath_counts/(rowSums(FeedingPath_counts))
# FeedingPath_props
# 
# FeedingPath_props <- as.dStratification_ata.frame(FeedingPath_props)
# 
# FeedingPath_props$Var1 <- factor(FeedingPath_props$Var1, levels = c("Reference", "Ocean", "Holomictic", "Meromictic"))
# 
# FeedingPath_plot <- ggplot(FeedingPath_props, mapping = aes(x= Var1, y= Freq, color = Var1, shape = row.names)) + 
#   geom_point(position = "identity", size = 5, aes(group = Var1)) +
#   scale_color_viridis(alpha = 0.5, end = 0.75, discrete = T, option = "G") +
#   theme_bw() +
#   theme(
#     plot.background = element_blank(),
#     panel.grid.major = element_blank(),
#     panel.grid.minor = element_blank(),
#     panel.border = element_blank(),
#     axis.line = element_line(color = "black")) +
#   ylab("Proportion") +
#   xlab("Site type")
# FeedingPath_plot
```


```{r, Stratification abundance weighted mean trait plots session info}
sessionInfo()
```
